// CLASS-SPECIFIC SPELL PROGRESSION SYSTEM
// Generated by Dungeon Editor on 2/20/2026, 5:49:24 PM

const CLASS_SPELL_TREES = {
};
if (typeof module !== 'undefined' && module.exports) { module.exports = { CLASS_SPELL_TREES }; }