// ═══════════════════════════════════════════════════════════════════════
// GAME VERSION FILE — gameversion.js
// Generated by Dungeon Editor on 2/20/2026, 5:54:49 PM
// ═══════════════════════════════════════════════════════════════════════

const GAME_VERSION = '2026.02.20-r34';

function checkGameVersion() {
    const stored = localStorage.getItem('dq_game_version');
    if (stored && stored !== GAME_VERSION) {
        const existing = document.getElementById('versionBanner');
        if (existing) return;
        const banner = document.createElement('div');
        banner.id = 'versionBanner';
        banner.innerHTML = `<div style="position:fixed;top:0;left:0;right:0;z-index:99999;background:#220000;border-bottom:3px solid #ff0000;padding:10px 16px;font-family:'VT323',monospace;display:flex;align-items:center;justify-content:space-between;gap:10px;box-sizing:border-box;"><div><span style="color:#ff4444;font-size:18px;font-weight:bold;">⚠ OUTDATED VERSION DETECTED</span><br><span style="color:#ff8888;font-size:14px;">You are running <strong style="color:#ffaaaa;">v${stored}</strong> — latest is <strong style="color:#00ff88;">v${GAME_VERSION}</strong>. Refresh now!</span></div><button onclick="location.reload(true)" style="background:#ff0000;color:#fff;border:2px solid #ff4444;padding:8px 16px;font-family:'VT323',monospace;font-size:16px;cursor:pointer;">🔄 REFRESH NOW</button></div>`;
        document.body.prepend(banner);
    }
    localStorage.setItem('dq_game_version', GAME_VERSION);
}

const REVISION_HISTORY = [

    {
        "version": "2026.02.21-r34",
        "date": "Feb 21, 2026",
        "summary": "Dungeon fix",
        "changes": [
            "Dungeon enemy balance changes including bosses."
        ]
    },

    {
        "version": "2026.02.21-r33",
        "date": "Feb 21, 2026",
        "summary": "Dungeon fix",
        "changes": [
            "Dungeon1 language for ladder fixed.  You can go UP/DOWN on the ladders."
        ]
    },

    {
        "version": "2026.02.20-r32",
        "date": "Feb 20, 2026",
        "summary": "new patch",
        "changes": [
            "Added: dungeon editor can now push to github."
        ]
    },
    {
        "version": "2026.02.20-r31",
        "date": "Feb 20, 2026",
        "summary": "New patch",
        "changes": [
            "Added: dungeon editor now can push to github"
        ]
    },
    {
        "version": "2026.02.20-r30",
        "date": "Feb 20, 2026",
        "summary": "Hunter pet save",
        "changes": [
            "Fix:  Hunter's pet was not saving."
        ]
    },
    {
        "version": "2025.02.19-r29",
        "date": "Feb 19, 2025",
        "summary": "Cleric healing spell issues",
        "changes": [
            "Healing spells are now min/max.  Potions stay static."
        ]
    },
    {
        "version": "2025.02.19-r28",
        "date": "Feb 19, 2025",
        "summary": "Cleric healing spell issues",
        "changes": [
            "Cleric healing spell was trying to target monster.  Now heals self."
        ]
    },
    {
        "version": "2025.02.19-r27",
        "date": "Feb 19, 2025",
        "summary": "Warrior shield update",
        "changes": [
            "Warrior shield was only active for one attack per encounter.  Fixed to entire encouter for all enemies."
        ]
    },
    {
        "version": "2025.02.19-r26",
        "date": "Feb 19, 2025",
        "summary": "Damage Rebalance, Warrior Shield, Dungeon Rarity System",
        "changes": [
            "Fixed: Legendary Wraith (Lv10) hitting Lv6 player for 245 — rarity multipliers were stacking 8×",
            "Rarity multipliers changed to flat +10% per tier: 1.0/1.1/1.2/1.3/1.4/1.5 (was 1.0/1.3/1.6/2.0/2.5/3.5)",
            "Shield button (🛡️) is now warrior-only — removed from all other classes",
            "Shield: 70% chance to halve all incoming damage; shows 🛡️ SHIELD! (−50%) on trigger",
            "Dungeon enemies no longer roll random rarity — quality is set in the room definition",
            "Dungeon1.js: all 77 enemies given explicit rarity (common/uncommon/rare/epic)"
        ]
    },
    {
        "version": "2025.02.19-r25",
        "date": "Feb 19, 2025",
        "summary": "Minor update",
        "changes": [
            "Changed temple name to just \"Temple\""
        ]
    },
    {
        "version": "2025.02.19-r24",
        "date": "Feb 19, 2025",
        "summary": "Minor updates",
        "changes": [
            "Drain life reduced from 50% to 25%",
            "Monster attack telegraph delay increased from 1s to 2s"
        ]
    },
    {
        "version": "2025.02.19-r23",
        "date": "Feb 19, 2025",
        "summary": "Class Master Audit — 3 Bug Fixes + Archer/Acolyte Masters Added",
        "changes": [
            "Fixed: Evolved players (Lv20+) lost master challenge buttons — now uses baseClass for key lookup",
            "Fixed: Riverside zone was locked with no master button — rewrote getMasterKeyForArea()",
            "Fixed: Archer and Acolyte had no class masters — permanently locked out of all zones",
            "Added 4 masters each for Archer and Acolyte (forest/plains/cave/crypt tiers)"
        ]
    },
    {
        "version": "2025.02.19-r22",
        "date": "Feb 19, 2025",
        "summary": "Bug Fix: /setlevel Soft-Lock + New /unlockmaster Command",
        "changes": [
            "Fixed: /setlevel bypassed class masters, soft-locking zone progression",
            "/setlevel now auto-defeats any master whose requiredLevel the player meets",
            "New sysop command: /unlockmaster [area|all] — retroactively fixes soft-locked characters"
        ]
    },
    {
        "version": "2025.02.19-r21",
        "date": "Feb 19, 2025",
        "summary": "Bug Fix: Tome & Orb Drops Equippable By Anyone",
        "changes": [
            "Fixed: tomes and orbs had no equip restriction — any class could equip them",
            "canUseWeapon() now restricts tome/orb/shadow_orb to spell classes only"
        ]
    },
    {
        "version": "2025.02.19-r20",
        "date": "Feb 19, 2025",
        "summary": "Bug Fix: Rogue Cannot Equip Dropped Daggers",
        "changes": [
            "Fixed: rogues could not equip procedurally dropped daggers",
            "canUseWeapon() now matches rogue-valid weapon types and name keywords"
        ]
    },
    {
        "version": "2025.02.18-r19",
        "date": "Feb 18, 2025",
        "summary": "Dungeon Enemy Levels Fixed + Monster Damage Ranges",
        "changes": [
            "Fixed: dungeon enemies were spawning at zone level instead of their template level",
            "Added minDamage/maxDamage to all 100+ monsters — damage rolls within a range per hit"
        ]
    },
    {
        "version": "2025.02.18-r18",
        "date": "Feb 18, 2025",
        "summary": "Dungeon entrance fixes",
        "changes": [
            "Return to town only available at dungeon entrance"
        ]
    },
    {
        "version": "2025.02.18-r16",
        "date": "Feb 18, 2025",
        "summary": "Hunter replaces Ranger",
        "changes": [
            "Ranger class removed and replaced by Hunter throughout codebase"
        ]
    },
    {
        "version": "2025.02.18-r15",
        "date": "Feb 18, 2025",
        "summary": "Hunter Trap Ability",
        "changes": [
            "New trap button (🪤) for hunters — costs 10 MP, slows enemy attacks 50% for entire combat",
            "15% chance to fail; only one trap per combat"
        ]
    },
    {
        "version": "2025.02.18-r14",
        "date": "Feb 18, 2025",
        "summary": "Healing Spells Out of Combat",
        "changes": [
            "Healing spells now castable from inventory (🎒) outside of combat"
        ]
    },
    {
        "version": "2025.02.18-r13",
        "date": "Feb 18, 2025",
        "summary": "Hunter Pet System + Weapon Modifiers for Spells",
        "changes": [
            "Hunter pets attack automatically after hunter; upgrade at Pet Trainer every 3 levels",
            "Pet chain: Dog → Wolf → Dire Wolf → Shadow Hound → Warg → Hellhound → Fenrir",
            "Weapon elemental modifiers now apply to all offensive spells"
        ]
    },
    {
        "version": "2025.02.18-r12",
        "date": "Feb 18, 2025",
        "summary": "Exploration zone fix",
        "changes": [
            "Riverside now available without beating Class Master"
        ]
    },
    {
        "version": "2025.02.18-r11",
        "date": "Feb 18, 2025",
        "summary": "Exploration zone fix",
        "changes": [
            "Fixed Riverside zone not loading correctly"
        ]
    },
    {
        "version": "2025.02.17-r10",
        "date": "Feb 17, 2025",
        "summary": "Class Masters Fix + Hunter Pet System",
        "changes": [
            "Added missing Warlock and Hunter class masters for all zones",
            "Hunter pets attack automatically; upgrade at Pet Trainer every 3 levels"
        ]
    },
    {
        "version": "2025.02.17-r9",
        "date": "Feb 17, 2025",
        "summary": "Dungeon Enemy Respawn",
        "changes": [
            "Dungeon enemies respawn 30 minutes after death in their original room"
        ]
    },
    {
        "version": "2025.02.17-r8",
        "date": "Feb 17, 2025",
        "summary": "Status Effect Stacking",
        "changes": [
            "Status effects now stack independently with separate DOT timers",
            "Stack count shown in messages: \"Poisoned [x2]\", \"Burning [x3]\""
        ]
    },
    {
        "version": "2025.02.17-r7",
        "date": "Feb 17, 2025",
        "summary": "Equipped Weapon Modifier Display",
        "changes": [
            "Weapon modifiers now display on equipped weapons in inventory"
        ]
    },
    {
        "version": "2025.02.17-r6",
        "date": "Feb 17, 2025",
        "summary": "Master Display Fix, Modifier Display, Spell Bonuses",
        "changes": [
            "Fixed: Forest zone always unlocks on Explore; masters show after /setlevel",
            "Weapon modifiers display in inventory and apply to all offensive spells"
        ]
    },
    {
        "version": "2025.02.17-r5",
        "date": "Feb 17, 2025",
        "summary": "Class Masters, Drop Rates, Combat UI Polish",
        "changes": [
            "Class masters now fully functional",
            "Weapon/armor drop rates increased from 2.5% to 4%",
            "Combat inventory button (🎒) shows unified potions/weapons/armor panel"
        ]
    },
    {
        "version": "2025.02.17-r4",
        "date": "Feb 17, 2025",
        "summary": "Version Check, Inventory Display, Zone Fixes",
        "changes": [
            "Version check runs on every town menu option",
            "All inventory items visible; unusable items dimmed with \"CANNOT EQUIP\"",
            "Fixed: Haunted Graveyard moved to Town2; Town1 shows only Forest and Riverside"
        ]
    },
    {
        "version": "2025.02.17-r3",
        "date": "Feb 17, 2025",
        "summary": "Enemy Join Fix, Instructions, UI Polish",
        "changes": [
            "Fixed: Enemies following into a room now appear instantly in combat",
            "Instructions expanded with rarity/quality color charts and drop mechanics"
        ]
    },
    {
        "version": "2025.02.17-r2",
        "date": "Feb 17, 2025",
        "summary": "Enemy AI, Inventory Overhaul, Spell Shop, Version System",
        "changes": [
            "Dungeon enemies follow and join active combat in real time",
            "Dungeon keys are permanent — never consumed or removed on exit",
            "Full-screen Dungeon Inventory: use potions, swap gear mid-dungeon",
            "Spell shop hides learned spells; shows locked spells as \"Coming Soon\"",
            "gameversion.js created; Revision History added to main menu"
        ]
    },
    {
        "version": "2025.02.17-r1",
        "date": "Feb 17, 2025",
        "summary": "Dungeon Maps, Combat Fixes, Shop & UI Polish",
        "changes": [
            "Dungeon map with trap [T] and start [H] markers; persists across floors and sessions",
            "/revealmap sysop command added",
            "Shop sell: duplicate items with different quality stack separately"
        ]
    },
    {
        "version": "2025.02.17-r0",
        "date": "Feb 17, 2025",
        "summary": "Rogue Rework, Spell/Wand Balance, Sysop Tools",
        "changes": [
            "Rogue double-strike and weapon restrictions reworked",
            "Wand/staff damage rebalanced; spell attack menu unified",
            "Hash-based sysop credential system; zone auto-unlock added to /setlevel"
        ]
    },
    {
        "version": "2025.02.16-r0",
        "date": "Feb 16, 2025",
        "summary": "UI Polish, Dungeon Editor, Shop Sell System",
        "changes": [
            "Shop sell system with sell value display",
            "Dungeon editor grid layout fixes; mobile character select improved"
        ]
    }
];