// ═══════════════════════════════════════════════════════════════════════
// GAME VERSION FILE — gameversion.js
// Generated by Dungeon Editor on 4/18/2026, 7:12:04 AM
// ═══════════════════════════════════════════════════════════════════════

const GAME_VERSION = '2026.04.18-r157';

function checkGameVersion() {
    const stored = localStorage.getItem('dq_game_version');
    if (stored && stored !== GAME_VERSION) {
        const existing = document.getElementById('versionBanner');
        if (existing) return;
        const banner = document.createElement('div');
        banner.id = 'versionBanner';
        banner.innerHTML = `<div style="position:fixed;top:0;left:0;right:0;z-index:99999;background:#220000;border-bottom:3px solid #ff0000;padding:10px 16px;font-family:'VT323',monospace;display:flex;align-items:center;justify-content:space-between;gap:10px;box-sizing:border-box;"><div><span style="color:#ff4444;font-size:18px;font-weight:bold;">⚠ OUTDATED VERSION DETECTED</span><br><span style="color:#ff8888;font-size:14px;">You are running <strong style="color:#ffaaaa;">v${stored}</strong> — latest is <strong style="color:#00ff88;">v${GAME_VERSION}</strong>. Refresh now!</span></div><button onclick="location.reload(true)" style="background:#ff0000;color:#fff;border:2px solid #ff4444;padding:8px 16px;font-family:'VT323',monospace;font-size:16px;cursor:pointer;">🔄 REFRESH NOW</button></div>`;
        document.body.prepend(banner);
    }
    localStorage.setItem('dq_game_version', GAME_VERSION);
}

const REVISION_HISTORY = [
    {
        "version": "2026.04.18-r157",
        "date": "Apr 18, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed:  Exploration zone unlocks for town 2 and town 3 are only lvl requirements now."
        ]
    },
    {
        "version": "2026.04.17-r156",
        "date": "Apr 17, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed: barbed",
            "Fixed: HP regen/turn (was ticking every second)",
            "Fixed: Inventory problems",
            "Fixed: After reloading back into exploration, enemies wouldn't attack automatically",
            "Fixed: High level class masters removed",
            "Fixed: All armor buffs should now be working"
        ]
    },
    {
        "version": "2026.04.17-r155",
        "date": "Apr 17, 2026",
        "summary": "New patch",
        "changes": [
            "Removed class masters from town 2 and town 3.  Now just a level unlock for exploring."
        ]
    },
    {
        "version": "2026.04.16-r154",
        "date": "Apr 16, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed: Weapon drops were not refreshing in the new inventory screens.",
            "Fixed: Using inventory from the exploration zone would return you to main town menu.",
            "Fixed: Staff pieces were able to pick up multiples."
        ]
    },
    {
        "version": "2026.04.16-r153",
        "date": "Apr 16, 2026",
        "summary": "New patch",
        "changes": [
            "Added: 2nd dungeon uploaded and working!"
        ]
    },
    {
        "version": "2026.04.15-r152",
        "date": "Apr 15, 2026",
        "summary": "New patch",
        "changes": [
            "Updated:  Changed support buttons in dungeons."
        ]
    },
    {
        "version": "2026.04.15-r151",
        "date": "Apr 15, 2026",
        "summary": "New patch",
        "changes": [
            "Re-implemented the new inventory system.",
            "Fixed a glitch where enemies would hit for double what was displayed.",
            "Added:  Out of combat spell casting, so you can heal out of combat."
        ]
    },
    {
        "version": "2026.04.15-r150",
        "date": "Apr 15, 2026",
        "summary": "New patch",
        "changes": [
            "reverting back to old code until all the bugs are working."
        ]
    },
    {
        "version": "2026.04.15-r149",
        "date": "Apr 15, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Any inventory button now pulls from the same inventory code to keep things normalized.",
            "ALSO, added a push and hold button on all weapons and armor to get more information about the abilities on the weapon/armor."
        ]
    },
    {
        "version": "2026.04.15-r148",
        "date": "Apr 15, 2026",
        "summary": "New patch",
        "changes": [
            "Updated:  Enemies now have separate, random timers.",
            "Armor drops were showing empty gem sockets.  This was removed.",
            "Several Armor buffs were added and are now all working!"
        ]
    },
    {
        "version": "2026.04.14-r147",
        "date": "Apr 14, 2026",
        "summary": "New patch",
        "changes": [
            "updating splash screen"
        ]
    },
    {
        "version": "2026.04.12-r146",
        "date": "Apr 12, 2026",
        "summary": "New patch",
        "changes": [
            "Added: New loading screen!"
        ]
    },
    {
        "version": "2026.04.12-r145",
        "date": "Apr 12, 2026",
        "summary": "New patch",
        "changes": [
            "Added: something new"
        ]
    },
    {
        "version": "2026.04.12-r144",
        "date": "Apr 12, 2026",
        "summary": "New patch",
        "changes": [
            "Added: New icon for iphone/android devices."
        ]
    },
    {
        "version": "2026.04.12-r143",
        "date": "Apr 12, 2026",
        "summary": "New patch",
        "changes": [
            "Gems were adding twice into weapons."
        ]
    },
    {
        "version": "2026.04.06-r142",
        "date": "Apr 6, 2026",
        "summary": "New patch",
        "changes": [
            "Just a quick update before bed.  Fixing some of the armor displays."
        ]
    },
    {
        "version": "2026.04.06-r141",
        "date": "Apr 6, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed: weapon and armor duplicates.  No more dupes when equipping or unequipping weapons and armor."
        ]
    },
    {
        "version": "2026.04.06-r140",
        "date": "Apr 6, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Major changes coming to armor!  New MP and HP stats, plus bonus abilities depending on quality!  There will be a balance coming for them, just implementing for now.  Only about 1/2 are currently working."
        ]
    },
    {
        "version": "2026.04.06-r139",
        "date": "Apr 6, 2026",
        "summary": "New patch",
        "changes": [
            "Rogue's double hit crit modifiers fixed.",
            "Also raised all crits to double damage for all player!"
        ]
    },
    {
        "version": "2026.04.05-r138",
        "date": "Apr 5, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Ashen Depths finished!"
        ]
    },
    {
        "version": "2026.04.05-r137",
        "date": "Apr 5, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Dungeon ladder functions now working."
        ]
    },
    {
        "version": "2026.04.05-r136",
        "date": "Apr 5, 2026",
        "summary": "New patch",
        "changes": [
            "Teleports were not working: fixed",
            "Monsters following in the dungeon were not working properly after teleport: Fixed",
            "Being stuck in the dungeon after refresh/restart: FIXED.  You should be stuck now properly.  (Take a recall potion!!)"
        ]
    },
    {
        "version": "2026.04.05-r135",
        "date": "Apr 5, 2026",
        "summary": "New Dungeon!",
        "changes": [
            "Added: ASHEN DEPTHS!!  New dungeon from town 2!  ENJOY!"
        ]
    },
    {
        "version": "2026.03.29-r134",
        "date": "Mar 29, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed:  Changed the HP multiplier for higher level enemies (nerfed it A LOT).  Enemies now have a more respectable HP, not overkill."
        ]
    },
    {
        "version": "2026.03.29-r133",
        "date": "Mar 29, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed bug:  Enemies were hitting for double damage from what was shown on screen."
        ]
    },
    {
        "version": "2026.03.28-r132",
        "date": "Mar 28, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed: CON stats give more base HP and will fix characters on reload.",
            "ALSO fixed: All status affects should be working properly now.",
            "HEADING TO BED, that was a long day!  -RavenMC"
        ]
    },
    {
        "version": "2026.03.28-r131",
        "date": "Mar 28, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Weapon modifiers are now fully functional!"
        ]
    },
    {
        "version": "2026.03.28-r130",
        "date": "Mar 28, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Vorpal one liners for combat."
        ]
    },
    {
        "version": "2026.03.28-r129",
        "date": "Mar 28, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Vorpal to weapons.  1% chance to insta-kill non boss enemies."
        ]
    },
    {
        "version": "2026.03.28-r128",
        "date": "Mar 28, 2026",
        "summary": "New patch",
        "changes": [
            "Balanced: Thanks to Commander for the tip:  Cloth and leather wearers are taking too little damage.  Damage % changed across the board for all types of armor."
        ]
    },
    {
        "version": "2026.03.28-r127",
        "date": "Mar 28, 2026",
        "summary": "New patch",
        "changes": [
            "FIXED:  Undefined names of weapons are now fixed on login."
        ]
    },
    {
        "version": "2026.03.28-r126",
        "date": "Mar 28, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed: game crashes while exploring and defeating enemies that drop weapons."
        ]
    },
    {
        "version": "2026.03.28-r125",
        "date": "Mar 28, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed:  function fixUndefinedModifiers was running too soon.  Unwrapped it and called it later after the restore function on login."
        ]
    },
    {
        "version": "2026.03.28-r124",
        "date": "Mar 28, 2026",
        "summary": "New patch",
        "changes": [
            "Weapon/armor strings are getting cleaned up better now for legacy weapons/armor.",
            "Updated naming of weapons.  Names were getting out of control (long) for higher end weapons.",
            "Updated sysop visual terminal commands."
        ]
    },
    {
        "version": "2026.03.27-r123",
        "date": "Mar 27, 2026",
        "summary": "New patch",
        "changes": [
            "Updating:  Weapons with gems are showing properly in the shops.  Equipped weapon and armor do not show up to sell in the shop so you don't accidentally sell those items."
        ]
    },
    {
        "version": "2026.03.27-r122",
        "date": "Mar 27, 2026",
        "summary": "New patch",
        "changes": [
            "FIXED: Gems that are socketed are now showing properly in inventory and in dungeon/exploration inventory screen!",
            "Weapons with undefined modifiers will now be re-created and restored as proper weapons including any gems the old weapon had AND will be properly equipped if it was equipped."
        ]
    },
    {
        "version": "2026.03.26-r121",
        "date": "Mar 26, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed: inventory was saving as strings, not objects.  Bug squashed"
        ]
    },
    {
        "version": "2026.03.26-r120",
        "date": "Mar 26, 2026",
        "summary": "New patch",
        "changes": [
            "Added: flags for equipped weapons after save and during reload.  Also magical butterknife can be equipped by all classes now."
        ]
    },
    {
        "version": "2026.03.26-r119",
        "date": "Mar 26, 2026",
        "summary": "New patch",
        "changes": [
            "Added: staying in an exploration area when over leveled will result in more enemies spawning per search *thank you to Sparkster for the idea!*"
        ]
    },
    {
        "version": "2026.03.26-r118",
        "date": "Mar 26, 2026",
        "summary": "New patch",
        "changes": [
            "Removed:  haptic feedback for now.  Apple doesn't support it in websites."
        ]
    },
    {
        "version": "2026.03.25-r117",
        "date": "Mar 25, 2026",
        "summary": "New patch",
        "changes": [
            "FIX: Full weapon names were not saving properly locally or in the cloud."
        ]
    },
    {
        "version": "2026.03.22-r116",
        "date": "Mar 22, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Dungeon keys to dungeon inventory screen!",
            "FIXED: Saving weapons to local or cloud storage now returns them correctly, even with modifiers."
        ]
    },
    {
        "version": "2026.03.22-r115",
        "date": "Mar 22, 2026",
        "summary": "New patch",
        "changes": [
            "Some broken weapons were not getting cleaned up *Thanks Sparkster for all the help and testing!*, should be fixed now."
        ]
    },
    {
        "version": "2026.03.22-r114",
        "date": "Mar 22, 2026",
        "summary": "New patch",
        "changes": [
            "Updated:  forcing enemies to drop certain weapons was causing the weapons to drop as strings.  Updated."
        ]
    },
    {
        "version": "2026.03.22-r113",
        "date": "Mar 22, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed:  Having multiple of the same gut gem would socket them all at one time to a weapon."
        ]
    },
    {
        "version": "2026.03.22-r112",
        "date": "Mar 22, 2026",
        "summary": "New patch",
        "changes": [
            "Patch: Updated admin commands to override any weapon quality"
        ]
    },
    {
        "version": "2026.03.22-r111",
        "date": "Mar 22, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed:  Gems and weapon bonuses now trigger on spells or melee attacks",
            "Fixed:  Characters were getting bonus stats when leveling instead of just points to spend.  Forced reset."
        ]
    },
    {
        "version": "2026.03.22-r110",
        "date": "Mar 22, 2026",
        "summary": "New patch",
        "changes": [
            "Force removed all weapons and armor that players had saved in game/local/cloud storage.",
            "Sell all items in the store: if the list is too long, its off screen and cant be clicked.",
            "Sell all items are now scrollable in the window."
        ]
    },
    {
        "version": "2026.03.22-r109",
        "date": "Mar 22, 2026",
        "summary": "New patch",
        "changes": [
            "Updated admin terminal commands to spawn objects, not strings.",
            "admin terminal now gives proper gems and attributes to spawned weapons",
            "Fixed featured weapons in the store to have modifiers and gems.",
            "REMOVED Orbs from the game for now, as they were causing string issues."
        ]
    },
    {
        "version": "2026.03.22-r108",
        "date": "Mar 22, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed corrupted items that were saving due to strings not objects."
        ]
    },
    {
        "version": "2026.03.22-r107",
        "date": "Mar 22, 2026",
        "summary": "New patch",
        "changes": [
            "Removed \"'\" from weapons and armor which was causing crashes.",
            "Some weapon drops were still being saved as strings not objects."
        ]
    },
    {
        "version": "2026.03.21-r106",
        "date": "Mar 21, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed:  broken exploration"
        ]
    },
    {
        "version": "2026.03.21-r105",
        "date": "Mar 21, 2026",
        "summary": "HUGE patch",
        "changes": [
            "New layout and design for the shops.",
            "Fixed old spells showing up to purchase for 0 gold.",
            "Fixed legacy weapons system (removed) as it was causing issues with inflated stats.",
            "Fixed Class Masters to object arrays instead of strings.",
            "UPDATED: Stats button in combat, shows players stats and enemies basic info.",
            "FIXED: Can now sell weapons and armor in the shop",
            "REMOVED: being able to put gems in armor (for now)",
            "Updated Dungeon editor to accept new object weapons, armor, items, etc...",
            "Updated Class masters to have mana pool for special abilities"
        ]
    },
    {
        "version": "2026.03.21-r104",
        "date": "Mar 21, 2026",
        "summary": "New patch",
        "changes": [
            "Updated:  Weapons arrays.  Each class has weapons they can use, cleaned up the code."
        ]
    },
    {
        "version": "2026.03.21-r103",
        "date": "Mar 21, 2026",
        "summary": "New patch",
        "changes": [
            "FIXED:  updating bounties after completion."
        ]
    },
    {
        "version": "2026.03.20-r102",
        "date": "Mar 20, 2026",
        "summary": "New patch",
        "changes": [
            "testing my github uploading program."
        ]
    },
    {
        "version": "2026.03.20-r101",
        "date": "Mar 20, 2026",
        "summary": "New patch",
        "changes": [
            "FIX:  Fixing the gem socketing functions."
        ]
    },
    {
        "version": "2026.03.17-r100",
        "date": "Mar 17, 2026",
        "summary": "New patch",
        "changes": [
            "PATCH:  Cleaning up weapon and armor syncing."
        ]
    },
    {
        "version": "2026.03.17-r99",
        "date": "Mar 17, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed:  you can now sell armor in the shop.",
            "Weapons with gems are worth more than stock weapon!"
        ]
    },
    {
        "version": "2026.03.17-r98",
        "date": "Mar 17, 2026",
        "summary": "New patch",
        "changes": [
            "FIXED: Blacksmith/socketing gems, now so the weapons true name."
        ]
    },
    {
        "version": "2026.03.16-r97",
        "date": "Mar 16, 2026",
        "summary": "New patch",
        "changes": [
            "Working on updating legacy armor."
        ]
    },
    {
        "version": "2026.03.15-r96",
        "date": "Mar 15, 2026",
        "summary": "New patch",
        "changes": [
            "Fixing inventory from exploring and dungeons."
        ]
    },
    {
        "version": "2026.03.14-r95",
        "date": "Mar 14, 2026",
        "summary": "New patch",
        "changes": [
            "Revamping weapon and armor system."
        ]
    },
    {
        "version": "2026.03.14-r94",
        "date": "Mar 14, 2026",
        "summary": "New patch",
        "changes": [
            "TONS of updates!  Added more quests with boss fights at the Guild",
            "Working on balancing the weapons."
        ]
    },
    {
        "version": "2026.03.12-r93",
        "date": "Mar 12, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed cloud backups.  Will backup on exit or reload of page.  Should also stop phone users from swiping the app closed, thus bypassing the cloud save."
        ]
    },
    {
        "version": "2026.03.10-r92",
        "date": "Mar 10, 2026",
        "summary": "New patch",
        "changes": [
            "Updated enemies and their \"spells/special attacks\""
        ]
    },
    {
        "version": "2026.03.09-r91",
        "date": "Mar 9, 2026",
        "summary": "New patch",
        "changes": [
            "Added:  Portal animations :)"
        ]
    },
    {
        "version": "2026.03.09-r90",
        "date": "Mar 9, 2026",
        "summary": "New patch",
        "changes": [
            "Bug fixes:  Bounties are now saved locally and can be saved on the cloud.",
            "When logging in through Cloud, it shows most recent played characters at the top instead of the bottom."
        ]
    },
    {
        "version": "2026.03.09-r89",
        "date": "Mar 9, 2026",
        "summary": "Update",
        "changes": [
            "Updated:  Bounties are preserved to your account.",
            "Bounties chance to find increased from 5% to 10%."
        ]
    },
    {
        "version": "2026.03.09-r88",
        "date": "Mar 9, 2026",
        "summary": "New patch",
        "changes": [
            "Added:  Cloud saves to town2 and town3"
        ]
    },
    {
        "version": "2026.03.09-r87",
        "date": "Mar 9, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed: Cut gem names are fixed",
            "Socketed gems are now showing damage done"
        ]
    },
    {
        "version": "2026.03.08-r86",
        "date": "Mar 8, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed: Damage calculations from bonus dmg on weapon not correct."
        ]
    },
    {
        "version": "2026.03.08-r85",
        "date": "Mar 8, 2026",
        "summary": "New patch",
        "changes": [
            "Adjusting the cloud saves:",
            "ALSO ADDED---> The GUILD!!  With quests that give rewards!!"
        ]
    },
    {
        "version": "2026.03.08-r84",
        "date": "Mar 8, 2026",
        "summary": "HUGE PATCH",
        "changes": [
            "Many changes, including showing your base damage + special weapon damage = total damage.",
            "Now allowing for CLOUD SAVES!!"
        ]
    },
    {
        "version": "2026.03.08-r83",
        "date": "Mar 8, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed lvl 20 spells being defined in two locations."
        ]
    },
    {
        "version": "2026.03.08-r82",
        "date": "Mar 8, 2026",
        "summary": "New patch",
        "changes": [
            "To weapons and armor, first stat is your base stats, and next line is your stats if equipping said weapon or armor."
        ]
    },
    {
        "version": "2026.03.08-r81",
        "date": "Mar 8, 2026",
        "summary": "New patch",
        "changes": [
            "Repairing the font issues"
        ]
    },
    {
        "version": "2026.03.07-r80",
        "date": "Mar 7, 2026",
        "summary": "New patch",
        "changes": [
            "Updated player stats screen to include buffs from weapons and armor."
        ]
    },
    {
        "version": "2026.03.07-r79",
        "date": "Mar 7, 2026",
        "summary": "New patch",
        "changes": [
            "Rogue fix on second hit."
        ]
    },
    {
        "version": "2026.03.07-r78",
        "date": "Mar 7, 2026",
        "summary": "Patch",
        "changes": [
            "Fixing Enemies MP pool."
        ]
    },
    {
        "version": "2026.03.07-r77",
        "date": "Mar 7, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed: Death Cultist would error when casting a spell at the player."
        ]
    },
    {
        "version": "2026.03.07-r76",
        "date": "Mar 7, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Shops require confirmation on sale.",
            "Inventory button while in dungeon or exploring now shows full details of weapons and armor."
        ]
    },
    {
        "version": "2026.03.06-r75",
        "date": "Mar 6, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Working on fixing Bounties in town-2."
        ]
    },
    {
        "version": "2026.03.06-r74",
        "date": "Mar 6, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Confirm sale in shops."
        ]
    },
    {
        "version": "2026.03.06-r73",
        "date": "Mar 6, 2026",
        "summary": "New patch",
        "changes": [
            "Updated coding on enemies casting spells crashing the game.  Should be fixed."
        ]
    },
    {
        "version": "2026.03.05-r72",
        "date": "Mar 5, 2026",
        "summary": "New patch",
        "changes": [
            "Add more choose your own adventures."
        ]
    },
    {
        "version": "2026.03.05-r71",
        "date": "Mar 5, 2026",
        "summary": "New patch",
        "changes": [
            "Raised the % of choose your own adventures. Also added many more."
        ]
    },
    {
        "version": "2026.03.05-r70",
        "date": "Mar 5, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed enemies rolling as \"undefined\" causing crash on kill before Lootroll."
        ]
    },
    {
        "version": "2026.03.05-r69",
        "date": "Mar 5, 2026",
        "summary": "buggy",
        "changes": [
            "Trying to work out some bugs in combat"
        ]
    },
    {
        "version": "2026.03.04-r68",
        "date": "Mar 4, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed:  Invetory button on town1 would click even when scrolling on phones."
        ]
    },
    {
        "version": "2026.03.03-r67",
        "date": "Mar 3, 2026",
        "summary": "Bugs",
        "changes": [
            "Still fixing bugs with Lore skip button"
        ]
    },
    {
        "version": "2026.03.03-r66",
        "date": "Mar 3, 2026",
        "summary": "New patch",
        "changes": [
            "Auto-scroll button in Lore moved from bottom of the letter to visible screen."
        ]
    },
    {
        "version": "2026.03.03-r65",
        "date": "Mar 3, 2026",
        "summary": "Bugs",
        "changes": [
            "Bugs:  Shop fix:  gold updating on pc, checking iphone"
        ]
    },
    {
        "version": "2026.03.03-r64",
        "date": "Mar 3, 2026",
        "summary": "Bugs again",
        "changes": [
            "Shop:  Player gold needs to update after purchase."
        ]
    },
    {
        "version": "2026.03.03-r63",
        "date": "Mar 3, 2026",
        "summary": "Bugs",
        "changes": [
            "More bug squishing"
        ]
    },
    {
        "version": "2026.03.03-r62",
        "date": "Mar 3, 2026",
        "summary": "New patch",
        "changes": [
            "Added: orientation lock when in fullscreen mode"
        ]
    },
    {
        "version": "2026.03.03-r61",
        "date": "Mar 3, 2026",
        "summary": "New patch",
        "changes": [
            "Bug squish:  Confirm purchase not showing on top."
        ]
    },
    {
        "version": "2026.03.03-r60",
        "date": "Mar 3, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Confirmation when making purchases."
        ]
    },
    {
        "version": "2026.03.02-r59",
        "date": "Mar 2, 2026",
        "summary": "New patch",
        "changes": [
            "Added: About & Contact page with my email address attached.  Please feel free to contact me with any suggestions, bugs that need squashed, or just plain feedback that is good or bad!  I will read all of them!  Thank you for any and all assistance!"
        ]
    },
    {
        "version": "2026.03.02-r58",
        "date": "Mar 2, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Terminal boarder flash when taking damage (toggle in settings)",
            "Game name changed to Calamity Dungeon as Dungeon Quest was just a short term name that I didn't know had already been used.  It served a purpose in the beginning."
        ]
    },
    {
        "version": "2026.03.02-r57",
        "date": "Mar 2, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Settings tab to the second and third town.",
            "Debug work for haptic feedback on iphone."
        ]
    },
    {
        "version": "2026.03.02-r56",
        "date": "Mar 2, 2026",
        "summary": "New patch",
        "changes": [
            "Added: Settings tab",
            "Text font slider for combat and town (for those clerics that needs reading glasses but are to stubborn to wear them :D",
            "BETA stages of haptic feedback for phones."
        ]
    },
    {
        "version": "2026.03.01-r55",
        "date": "Mar 1, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed hard to read text, changed colors to something more brighter.",
            "Added confirm purchases due to accidental purchases (by a Cleric that will go un-named) :)"
        ]
    },
    {
        "version": "2026.03.01-r54",
        "date": "Mar 1, 2026",
        "summary": "New patch",
        "changes": [
            "Ashen Harbor revamp!",
            "Now has a Bounty Board!  Complete bounties to collect rewards!",
            "Portals now fixed to all 3 towns."
        ]
    },
    {
        "version": "2026.02.28-r53",
        "date": "Feb 28, 2026",
        "summary": "New patch",
        "changes": [
            "Potions maxstack is 10 each.  Can be sold back to Shop.  (wont auto-sell with on click)",
            "Some enemies weren't dropping items as they should.",
            "Some cut/socketed gems were not giving the full buffs.",
            "Goblin's special ability was not hitting.",
            "Sysop debug terminal now working properly with melee and spells."
        ]
    },
    {
        "version": "2026.02.28-r52",
        "date": "Feb 28, 2026",
        "summary": "Updates",
        "changes": [
            "Added:  Giving enemies abilities/spells and also MP.  Lots of new abilities coming for the enemies.",
            "More junk items to sell (for now)."
        ]
    },
    {
        "version": "2026.02.28-r51",
        "date": "Feb 28, 2026",
        "summary": "New patch",
        "changes": [
            "Bestiary fix.  Clicking on the enemy would not show details."
        ]
    },
    {
        "version": "2026.02.27-r50",
        "date": "Feb 27, 2026",
        "summary": "New MAJOR patch!!!",
        "changes": [
            "Lore ADDED!!  Should add depth to the game!  Thank you Jim!",
            "Added Bestiary under Character Stats",
            "Added Lore history under Character Stats",
            "Added Lore screen for already created characters",
            "Added sysop debugging mode to test drop rates, etc..."
        ]
    },
    {
        "version": "2026.02.25-r49",
        "date": "Feb 25, 2026",
        "summary": "New patch",
        "changes": [
            "Moving hp/mp bars to better location."
        ]
    },
    {
        "version": "2026.02.25-r48",
        "date": "Feb 25, 2026",
        "summary": "New patch",
        "changes": [
            "HP and MP bars are now more like the XP bar."
        ]
    },
    {
        "version": "2026.02.24-r47",
        "date": "Feb 24, 2026",
        "summary": "Big update",
        "changes": [
            "Many new updates and features.",
            "Fixed XP bar for iphones.",
            "Gems replaced with crystals, as new gems are being implemented and it removes confusion.",
            "New weapons and armor added for all classes that contain empty socks for \"cut\" gems",
            "Added blacksmith to cut gems and socket gems into weapons and armor.",
            "Fixed new gem drop rate.",
            "Moved inventory \"exit\" button to the bottom to make it easier to find.",
            "Fixed inventory full screen bug, now its the same size as the game on PC.",
            "Added glowing melee button for RUNESTRIKE on the Runesmith class.",
            "Now allows mana to regen while using melee attacks (after 15 seconds)."
        ]
    },
    {
        "version": "2026.02.23-r46",
        "date": "Feb 23, 2026",
        "summary": "New patch",
        "changes": [
            "On level-up, there is now a button inside your inventory that will allow you to use your upgrade points immediately instead of waiting to get back to town."
        ]
    },
    {
        "version": "2026.02.23-r45",
        "date": "Feb 23, 2026",
        "summary": "Armor update",
        "changes": [
            "Armor reduction changed from fixed to percentage.  Cloth should feel more like cloth now."
        ]
    },
    {
        "version": "2026.02.23-r44",
        "date": "Feb 23, 2026",
        "summary": "New patch",
        "changes": [
            "On the iPhone, the buttons were too close to the bottom of the screen. The XP bar was moved to the bottom to absorb the iPhone button."
        ]
    },
    {
        "version": "2026.02.23-r43",
        "date": "Feb 23, 2026",
        "summary": "New patch",
        "changes": [
            "Fixed Runesmith's armor and weapons pool."
        ]
    },
    {
        "version": "2026.02.23-r42",
        "date": "Feb 23, 2026",
        "summary": "Update",
        "changes": [
            "Bug fixes:  Gem slots not showing up in the correct weapons.",
            "New character bug fixes."
        ]
    },
    {
        "version": "2026.02.22-r41",
        "date": "Feb 22, 2026",
        "summary": "New class and runestones",
        "changes": [
            "Adding a new class and a new weapon mechanic, gem stones. Some weapons will have empty gem slots. Find the uncut gem stones, have them cut and customize your rare weapon to make it even more powerful!"
        ]
    },
    {
        "version": "2026.02.22-r40",
        "date": "Feb 22, 2026",
        "summary": "New charecter",
        "changes": [
            "Added: Runesmith!  Beta stages. Will be rolled out in stages."
        ]
    },
    {
        "version": "2026.02.21-r39",
        "date": "Feb 21, 2026",
        "summary": "Acolyte code removed",
        "changes": [
            "Acolyte code removed.  Cleric is now glass cannon. Can hit very low and very high!  More exciting!"
        ]
    },
    {
        "version": "2026.02.21-r38",
        "date": "Feb 21, 2026",
        "summary": "Town 3",
        "changes": [
            "Working on Town3.  Will be building Dungeon2 soon."
        ]
    },
    {
        "version": "2026.02.21-r37",
        "date": "Feb 21, 2026",
        "summary": "Heavy Melee",
        "changes": [
            "Heavy Melee needed a balance change.  Down to 15% from 35%."
        ]
    },
    {
        "version": "2026.02.21-r37",
        "date": "Feb 21, 2026",
        "summary": "Town-3 added",
        "changes": [
            "Town 3 is added, but not live yet.  Crossroads of the Worlds!"
        ]
    },
    {
        "version": "2026.02.21-r36",
        "date": "Feb 21, 2026",
        "summary": "Cleric update",
        "changes": [
            "Cleric should have same mana pool as Mage.  Buffed starting MP to 100 from 70.  Should update to already created charecters.",
            "Clerics mana costs for damage spells lowered across the board."
        ]
    },
    {
        "version": "2026.02.21-r35",
        "date": "Feb 21, 2026",
        "summary": "Dungeon balance enemy fix",
        "changes": [
            "There was a level bonus given to enemies for each level difference, that has been nerfed.  Also the rarity of the enemy was compounding an those numbers as well which was causing very high damage numbers.",
            "Enemies with EPIC would get two swings, this was nerfed back to one."
        ]
    },
    {
        "version": "2026.02.21-r34",
        "date": "Feb 21, 2026",
        "summary": "Dungeon fix",
        "changes": [
            "Dungeon enemy balance changes including bosses."
        ]
    },
    {
        "version": "2026.02.21-r33",
        "date": "Feb 21, 2026",
        "summary": "Dungeon fix",
        "changes": [
            "Dungeon1 language for ladder fixed.  You can go UP/DOWN on the ladders."
        ]
    },
    {
        "version": "2026.02.20-r32",
        "date": "Feb 20, 2026",
        "summary": "new patch",
        "changes": [
            "Added: dungeon editor can now push to github."
        ]
    },
    {
        "version": "2026.02.20-r30",
        "date": "Feb 20, 2026",
        "summary": "Hunter pet save",
        "changes": [
            "Fix:  Hunter's pet was not saving."
        ]
    },
    {
        "version": "2025.02.19-r29",
        "date": "Feb 19, 2025",
        "summary": "Cleric healing spell issues",
        "changes": [
            "Healing spells are now min/max.  Potions stay static."
        ]
    },
    {
        "version": "2025.02.19-r28",
        "date": "Feb 19, 2025",
        "summary": "Cleric healing spell issues",
        "changes": [
            "Cleric healing spell was trying to target monster.  Now heals self."
        ]
    },
    {
        "version": "2025.02.19-r27",
        "date": "Feb 19, 2025",
        "summary": "Warrior shield update",
        "changes": [
            "Warrior shield was only active for one attack per encounter.  Fixed to entire encouter for all enemies."
        ]
    },
    {
        "version": "2025.02.19-r26",
        "date": "Feb 19, 2025",
        "summary": "Damage Rebalance, Warrior Shield, Dungeon Rarity System",
        "changes": [
            "Fixed: Legendary Wraith (Lv10) hitting Lv6 player for 245 — rarity multipliers were stacking 8×",
            "Rarity multipliers changed to flat +10% per tier: 1.0/1.1/1.2/1.3/1.4/1.5 (was 1.0/1.3/1.6/2.0/2.5/3.5)",
            "Shield button (🛡️) is now warrior-only — removed from all other classes",
            "Shield: 70% chance to halve all incoming damage; shows 🛡️ SHIELD! (−50%) on trigger",
            "Dungeon enemies no longer roll random rarity — quality is set in the room definition",
            "Dungeon1.js: all 77 enemies given explicit rarity (common/uncommon/rare/epic)"
        ]
    },
    {
        "version": "2025.02.19-r25",
        "date": "Feb 19, 2025",
        "summary": "Minor update",
        "changes": [
            "Changed temple name to just \"Temple\""
        ]
    },
    {
        "version": "2025.02.19-r24",
        "date": "Feb 19, 2025",
        "summary": "Minor updates",
        "changes": [
            "Drain life reduced from 50% to 25%",
            "Monster attack telegraph delay increased from 1s to 2s"
        ]
    },
    {
        "version": "2025.02.19-r23",
        "date": "Feb 19, 2025",
        "summary": "Class Master Audit — 3 Bug Fixes + Archer/Acolyte Masters Added",
        "changes": [
            "Fixed: Evolved players (Lv20+) lost master challenge buttons — now uses baseClass for key lookup",
            "Fixed: Riverside zone was locked with no master button — rewrote getMasterKeyForArea()",
            "Fixed: Archer and Acolyte had no class masters — permanently locked out of all zones",
            "Added 4 masters each for Archer and Acolyte (forest/plains/cave/crypt tiers)"
        ]
    },
    {
        "version": "2025.02.19-r22",
        "date": "Feb 19, 2025",
        "summary": "Bug Fix: /setlevel Soft-Lock + New /unlockmaster Command",
        "changes": [
            "Fixed: /setlevel bypassed class masters, soft-locking zone progression",
            "/setlevel now auto-defeats any master whose requiredLevel the player meets",
            "New sysop command: /unlockmaster [area|all] — retroactively fixes soft-locked characters"
        ]
    },
    {
        "version": "2025.02.19-r21",
        "date": "Feb 19, 2025",
        "summary": "Bug Fix: Tome & Orb Drops Equippable By Anyone",
        "changes": [
            "Fixed: tomes and orbs had no equip restriction — any class could equip them",
            "canUseWeapon() now restricts tome/orb/shadow_orb to spell classes only"
        ]
    },
    {
        "version": "2025.02.19-r20",
        "date": "Feb 19, 2025",
        "summary": "Bug Fix: Rogue Cannot Equip Dropped Daggers",
        "changes": [
            "Fixed: rogues could not equip procedurally dropped daggers",
            "canUseWeapon() now matches rogue-valid weapon types and name keywords"
        ]
    },
    {
        "version": "2025.02.18-r19",
        "date": "Feb 18, 2025",
        "summary": "Dungeon Enemy Levels Fixed + Monster Damage Ranges",
        "changes": [
            "Fixed: dungeon enemies were spawning at zone level instead of their template level",
            "Added minDamage/maxDamage to all 100+ monsters — damage rolls within a range per hit"
        ]
    },
    {
        "version": "2025.02.18-r18",
        "date": "Feb 18, 2025",
        "summary": "Dungeon entrance fixes",
        "changes": [
            "Return to town only available at dungeon entrance"
        ]
    },
    {
        "version": "2025.02.18-r16",
        "date": "Feb 18, 2025",
        "summary": "Hunter replaces Ranger",
        "changes": [
            "Ranger class removed and replaced by Hunter throughout codebase"
        ]
    },
    {
        "version": "2025.02.18-r15",
        "date": "Feb 18, 2025",
        "summary": "Hunter Trap Ability",
        "changes": [
            "New trap button (🪤) for hunters — costs 10 MP, slows enemy attacks 50% for entire combat",
            "15% chance to fail; only one trap per combat"
        ]
    },
    {
        "version": "2025.02.18-r14",
        "date": "Feb 18, 2025",
        "summary": "Healing Spells Out of Combat",
        "changes": [
            "Healing spells now castable from inventory (🎒) outside of combat"
        ]
    },
    {
        "version": "2025.02.18-r13",
        "date": "Feb 18, 2025",
        "summary": "Hunter Pet System + Weapon Modifiers for Spells",
        "changes": [
            "Hunter pets attack automatically after hunter; upgrade at Pet Trainer every 3 levels",
            "Pet chain: Dog → Wolf → Dire Wolf → Shadow Hound → Warg → Hellhound → Fenrir",
            "Weapon elemental modifiers now apply to all offensive spells"
        ]
    },
    {
        "version": "2025.02.18-r12",
        "date": "Feb 18, 2025",
        "summary": "Exploration zone fix",
        "changes": [
            "Riverside now available without beating Class Master"
        ]
    },
    {
        "version": "2025.02.18-r11",
        "date": "Feb 18, 2025",
        "summary": "Exploration zone fix",
        "changes": [
            "Fixed Riverside zone not loading correctly"
        ]
    },
    {
        "version": "2025.02.17-r10",
        "date": "Feb 17, 2025",
        "summary": "Class Masters Fix + Hunter Pet System",
        "changes": [
            "Added missing Warlock and Hunter class masters for all zones",
            "Hunter pets attack automatically; upgrade at Pet Trainer every 3 levels"
        ]
    },
    {
        "version": "2025.02.17-r9",
        "date": "Feb 17, 2025",
        "summary": "Dungeon Enemy Respawn",
        "changes": [
            "Dungeon enemies respawn 30 minutes after death in their original room"
        ]
    },
    {
        "version": "2025.02.17-r8",
        "date": "Feb 17, 2025",
        "summary": "Status Effect Stacking",
        "changes": [
            "Status effects now stack independently with separate DOT timers",
            "Stack count shown in messages: \"Poisoned [x2]\", \"Burning [x3]\""
        ]
    },
    {
        "version": "2025.02.17-r7",
        "date": "Feb 17, 2025",
        "summary": "Equipped Weapon Modifier Display",
        "changes": [
            "Weapon modifiers now display on equipped weapons in inventory"
        ]
    },
    {
        "version": "2025.02.17-r6",
        "date": "Feb 17, 2025",
        "summary": "Master Display Fix, Modifier Display, Spell Bonuses",
        "changes": [
            "Fixed: Forest zone always unlocks on Explore; masters show after /setlevel",
            "Weapon modifiers display in inventory and apply to all offensive spells"
        ]
    },
    {
        "version": "2025.02.17-r5",
        "date": "Feb 17, 2025",
        "summary": "Class Masters, Drop Rates, Combat UI Polish",
        "changes": [
            "Class masters now fully functional",
            "Weapon/armor drop rates increased from 2.5% to 4%",
            "Combat inventory button (🎒) shows unified potions/weapons/armor panel"
        ]
    },
    {
        "version": "2025.02.17-r4",
        "date": "Feb 17, 2025",
        "summary": "Version Check, Inventory Display, Zone Fixes",
        "changes": [
            "Version check runs on every town menu option",
            "All inventory items visible; unusable items dimmed with \"CANNOT EQUIP\"",
            "Fixed: Haunted Graveyard moved to Town2; Town1 shows only Forest and Riverside"
        ]
    },
    {
        "version": "2025.02.17-r3",
        "date": "Feb 17, 2025",
        "summary": "Enemy Join Fix, Instructions, UI Polish",
        "changes": [
            "Fixed: Enemies following into a room now appear instantly in combat",
            "Instructions expanded with rarity/quality color charts and drop mechanics"
        ]
    },
    {
        "version": "2025.02.17-r2",
        "date": "Feb 17, 2025",
        "summary": "Enemy AI, Inventory Overhaul, Spell Shop, Version System",
        "changes": [
            "Dungeon enemies follow and join active combat in real time",
            "Dungeon keys are permanent — never consumed or removed on exit",
            "Full-screen Dungeon Inventory: use potions, swap gear mid-dungeon",
            "Spell shop hides learned spells; shows locked spells as \"Coming Soon\"",
            "gameversion.js created; Revision History added to main menu"
        ]
    },
    {
        "version": "2025.02.17-r1",
        "date": "Feb 17, 2025",
        "summary": "Dungeon Maps, Combat Fixes, Shop & UI Polish",
        "changes": [
            "Dungeon map with trap [T] and start [H] markers; persists across floors and sessions",
            "/revealmap sysop command added",
            "Shop sell: duplicate items with different quality stack separately"
        ]
    },
    {
        "version": "2025.02.17-r0",
        "date": "Feb 17, 2025",
        "summary": "Rogue Rework, Spell/Wand Balance, Sysop Tools",
        "changes": [
            "Rogue double-strike and weapon restrictions reworked",
            "Wand/staff damage rebalanced; spell attack menu unified",
            "Hash-based sysop credential system; zone auto-unlock added to /setlevel"
        ]
    },
    {
        "version": "2025.02.16-r0",
        "date": "Feb 16, 2025",
        "summary": "UI Polish, Dungeon Editor, Shop Sell System",
        "changes": [
            "Shop sell system with sell value display",
            "Dungeon editor grid layout fixes; mobile character select improved"
        ]
    }
];