// ═══════════════════════════════════════════════════════════════
// items.js - Items Database
// Generated by Dungeon Editor on 2/21/2026, 6:33:08 PM
// ═══════════════════════════════════════════════════════════════

const ITEMS = {
    ancient_map: {
        "name": "Ancient Map",
        "subtype": "quest",
        "power": 0,
        "cost": 0,
        "sellValue": 5,
        "description": "A crumbling map with cryptic markings.",
        "icon": "📜"
    },
    ancient_relic: {
        "name": "Ancient Relic",
        "subtype": "quest",
        "power": 0,
        "cost": 0,
        "description": "Quest item"
    },
    berserker_rage: {
        "name": "Berserker Rage",
        "subtype": "buff_damage",
        "power": 50,
        "duration": 180000,
        "cost": 800,
        "description": "+50% DMG (3min)"
    },
    bone_key: {
        "name": "Bone Key",
        "subtype": "dungeon_key",
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "description": "A gnarly bone key. Opens bone-locked dungeon doors.",
        "icon": "🗝",
        "keyType": "bone"
    },
    brass_key: {
        "name": "Brass Key",
        "subtype": "dungeon_key",
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "description": "A polished brass key. Opens brass-locked dungeon doors.",
        "icon": "🗝",
        "keyType": "brass"
    },
    bronze_key: {
        "name": "Bronze Key",
        "subtype": "dungeon_key",
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "description": "A tarnished bronze key. Opens bronze-locked dungeon doors.",
        "icon": "🗝",
        "keyType": "bronze"
    },
    copper_key: {
        "name": "Copper Key",
        "subtype": "dungeon_key",
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "description": "A worn copper key. Opens copper-locked dungeon doors.",
        "icon": "🗝",
        "keyType": "copper"
    },
    defense_potion: {
        "name": "Defense Elixir",
        "subtype": "buff_def",
        "power": 10,
        "duration": 300000,
        "cost": 200,
        "description": "+10 DEF (5min)"
    },
    diamond_key: {
        "name": "Diamond Key",
        "subtype": "dungeon_key",
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "description": "A pristine diamond key. Opens diamond-locked dungeon doors.",
        "icon": "🗝",
        "keyType": "diamond"
    },
    dragon_scale: {
        "name": "Dragon Scale",
        "subtype": "material",
        "power": 0,
        "cost": 200,
        "description": "Epic crafting material"
    },
    dungeon_note: {
        "name": "Dungeon Note",
        "subtype": "quest",
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "description": "A scrawled note left by a previous explorer.",
        "icon": "📄"
    },
    electrum_key: {
        "name": "Electrum Key",
        "subtype": "dungeon_key",
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "description": "An unusual electrum key. Opens electrum-locked dungeon doors.",
        "icon": "🗝",
        "keyType": "electrum"
    },
    elixir: {
        "name": "Elixir",
        "subtype": "full_restore",
        "power": 0,
        "cost": 300,
        "description": "Full HP/MP"
    },
    gold_boost_potion: {
        "name": "Gold Boost",
        "subtype": "buff_gold",
        "power": 30,
        "duration": 900000,
        "cost": 500,
        "description": "+30% Gold (15min)"
    },
    greater_defense_potion: {
        "name": "Greater DEF",
        "subtype": "buff_def",
        "power": 20,
        "duration": 300000,
        "cost": 400,
        "description": "+20 DEF (5min)"
    },
    greater_health_potion: {
        "name": "Greater Health",
        "subtype": "heal_hp",
        "power": 100,
        "cost": 100,
        "description": "+100 HP"
    },
    greater_mana_potion: {
        "name": "Greater Mana",
        "subtype": "heal_mp",
        "power": 80,
        "cost": 120,
        "description": "+80 MP"
    },
    greater_strength_potion: {
        "name": "Greater STR",
        "subtype": "buff_str",
        "power": 20,
        "duration": 300000,
        "cost": 400,
        "description": "+20 STR (5min)"
    },
    greater_exp_potion: {
        "name": "Greater XP",
        "subtype": "buff_xp",
        "power": 50,
        "duration": 900000,
        "cost": 1000,
        "description": "+50% XP (15min)"
    },
    speed_potion: {
        "name": "Haste Potion",
        "subtype": "buff_speed",
        "power": 20,
        "duration": 300000,
        "cost": 250,
        "description": "+20% Speed (5min)"
    },
    health_potion: {
        "name": "Health Potion",
        "subtype": "heal_hp",
        "power": 50,
        "cost": 50,
        "description": "+50 HP"
    },
    iron_key: {
        "name": "Iron Key",
        "subtype": "dungeon_key",
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "description": "A heavy iron key. Opens iron-locked dungeon doors.",
        "icon": "🗝",
        "keyType": "iron"
    },
    large_gem: {
        "name": "Large Gem",
        "subtype": "material",
        "power": 0,
        "cost": 50,
        "sellValue": 25,
        "description": "A fine quality gem. Merchants pay well for these."
    },
    lucky_charm: {
        "name": "Lucky Charm",
        "subtype": "buff_luck",
        "power": 20,
        "duration": 600000,
        "cost": 400,
        "description": "+20 LCK (10min)"
    },
    magic_potion: {
        "name": "Magic Elixir",
        "subtype": "buff_magic",
        "power": 15,
        "duration": 300000,
        "cost": 250,
        "description": "+15 MAG (5min)"
    },
    mana_potion: {
        "name": "Mana Potion",
        "subtype": "heal_mp",
        "power": 40,
        "cost": 60,
        "description": "+40 MP"
    },
    obsidian_key: {
        "name": "Obsidian Key",
        "subtype": "dungeon_key",
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "description": "A dark obsidian key. Opens obsidian-locked dungeon doors.",
        "icon": "🗝",
        "keyType": "obsidian"
    },
    critical_potion: {
        "name": "Precision Elixir",
        "subtype": "buff_crit",
        "power": 15,
        "duration": 300000,
        "cost": 300,
        "description": "+15% Crit (5min)"
    },
    recall_potion: {
        "name": "Recall Potion",
        "subtype": "recall",
        "power": 0,
        "cost": 5000,
        "sellValue": 0,
        "maxStack": 1,
        "description": "Instantly return to town from any dungeon.",
        "icon": "🌀",
        "lore": "A swirling vial of homeward magic. One sip and you are gone."
    },
    regeneration_potion: {
        "name": "Regeneration",
        "subtype": "buff_regen",
        "power": 10,
        "duration": 300000,
        "cost": 500,
        "description": "+10 HP/sec (5min)"
    },
    ruby_key: {
        "name": "Ruby Key",
        "subtype": "dungeon_key",
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "description": "A crimson ruby key. Opens ruby-locked dungeon doors.",
        "icon": "🗝",
        "keyType": "ruby"
    },
    rune_fragment: {
        "name": "Rune Fragment",
        "subtype": "material",
        "power": 0,
        "cost": 0,
        "sellValue": 25,
        "description": "A shard of ancient rune stone. Seems valuable.",
        "icon": "✦"
    },
    silver_key: {
        "name": "Silver Key",
        "subtype": "dungeon_key",
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "description": "A gleaming silver key. Opens silver-locked dungeon doors.",
        "icon": "🗝",
        "keyType": "silver"
    },
    small_gem: {
        "name": "Small Gem",
        "subtype": "material",
        "power": 0,
        "cost": 10,
        "sellValue": 5,
        "description": "A glittering gem. Worth a few coins to the right merchant."
    },
    staff_piece_1: {
        "name": "Staff Piece I — The Base",
        "subtype": "staff_piece",
        "staffPieceNumber": 1,
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "maxStack": 1,
        "icon": "🪄",
        "description": "A gnarled obsidian base, humming faintly with trapped energy.",
        "lore": "The first of eight. The journey of a thousand years begins here."
    },
    staff_piece_2: {
        "name": "Staff Piece II — The Shaft",
        "subtype": "staff_piece",
        "staffPieceNumber": 2,
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "maxStack": 1,
        "icon": "🪄",
        "description": "A length of petrified dragon-wood, warm to the touch.",
        "lore": "Carved from a tree that grew beside a dragon's lair for five centuries."
    },
    staff_piece_3: {
        "name": "Staff Piece III — The Binding",
        "subtype": "staff_piece",
        "staffPieceNumber": 3,
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "maxStack": 1,
        "icon": "🪄",
        "description": "Coils of ancient copper wire wrapped in worn leather strips.",
        "lore": "These bindings once held together a weapon of immeasurable power."
    },
    staff_piece_4: {
        "name": "Staff Piece IV — The Rune Ring",
        "subtype": "staff_piece",
        "staffPieceNumber": 4,
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "maxStack": 1,
        "icon": "🪄",
        "description": "A ring of carved rune-stone that crackles with static.",
        "lore": "The runes shift when no one is watching. Do not look away."
    },
    staff_piece_5: {
        "name": "Staff Piece V — The Conduit",
        "subtype": "staff_piece",
        "staffPieceNumber": 5,
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "maxStack": 1,
        "icon": "🪄",
        "description": "A hollow crystal tube that channels raw magical current.",
        "lore": "Touch it and feel the pulse of something ancient and hungry."
    },
    staff_piece_6: {
        "name": "Staff Piece VI — The Focus Lens",
        "subtype": "staff_piece",
        "staffPieceNumber": 6,
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "maxStack": 1,
        "icon": "🪄",
        "description": "A fractured emerald lens that bends light unnaturally.",
        "lore": "Stare through it too long and you may see where the staff wants to take you."
    },
    staff_piece_7: {
        "name": "Staff Piece VII — The Collar",
        "subtype": "staff_piece",
        "staffPieceNumber": 7,
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "maxStack": 1,
        "icon": "🪄",
        "description": "A tight silver collar etched with celestial star maps.",
        "lore": "The stars it depicts do not match any known sky."
    },
    staff_piece_8: {
        "name": "Staff Piece VIII — The Crown Gem",
        "subtype": "staff_piece",
        "staffPieceNumber": 8,
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "maxStack": 1,
        "icon": "🪄",
        "description": "A pulsing violet gemstone that hovers above your palm.",
        "lore": "The final piece. It trembles in your hand, eager to be reunited with the others."
    },
    invulnerability_potion: {
        "name": "Stone Skin",
        "subtype": "buff_invuln",
        "power": 50,
        "duration": 120000,
        "cost": 1000,
        "description": "+50% Resist (2min)"
    },
    strength_potion: {
        "name": "Strength Elixir",
        "subtype": "buff_str",
        "power": 10,
        "duration": 300000,
        "cost": 200,
        "description": "+10 STR (5min)"
    },
    superior_health_potion: {
        "name": "Superior Health",
        "subtype": "heal_hp",
        "power": 200,
        "cost": 200,
        "description": "+200 HP"
    },
    superior_mana_potion: {
        "name": "Superior Mana",
        "subtype": "heal_mp",
        "power": 150,
        "cost": 250,
        "description": "+150 MP"
    },
    topaz_key: {
        "name": "Topaz Key",
        "subtype": "dungeon_key",
        "power": 0,
        "cost": 0,
        "sellValue": 0,
        "description": "An amber topaz key. Opens topaz-locked dungeon doors.",
        "icon": "🗝",
        "keyType": "topaz"
    },
    exp_potion: {
        "name": "XP Boost",
        "subtype": "buff_xp",
        "power": 25,
        "duration": 900000,
        "cost": 500,
        "description": "+25% XP (15min)"
    }
};

console.log('✅ Items loaded:', Object.keys(ITEMS).length, 'items');