// WEAPONS DATABASE
// Complete rewritten version with proper stats and no duplicates

const QUALITY_CONFIG = {
    poor:      { bonusPct: 0.00, color: '#808080', name: 'Poor'      },
    normal:    { bonusPct: 0.10, color: '#00FF00', name: 'Normal'    },
    rare:      { bonusPct: 0.25, color: '#0099FF', name: 'Rare'      },
    epic:      { bonusPct: 0.40, color: '#9933FF', name: 'Epic'      },
    legendary: { bonusPct: 0.60, color: '#FF9900', name: 'Legendary' },
    godly:     { bonusPct: 0.85, color: '#FF0000', name: 'Godly'     }
};

const WEAPONS = {

    // ======================================================
    // UNARMED
    // ======================================================
    bare_fists: {
        "name": "Bare Fists",
        "baseDamage": 0,
        "maxDamage": 0,
        "baseMagicDamage": 0,
        "level": 1,
        "quality": "poor",
        "type": "unarmed",
        "cost": 0,
        "description": "No weapon equipped. Damage comes from raw strength alone.",
        "unarmed": true
    },

    // ======================================================
    // WANDS - Mage/Warlock (Very Low Melee, High Magic)
    // ======================================================
    apprentice_wand: {
        "name": "Apprentice Wand",
        "baseDamage": 1,
        "maxDamage": 3,
        "baseMagicDamage": 8,
        "cost": 80,
        "level": 1,
        "quality": "normal",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror", "necrolyte"],
        "weaponSubtype": "wand"
    },
    focus_wand: {
        "name": "Focus Wand",
        "baseDamage": 1,
        "maxDamage": 3,
        "baseMagicDamage": 11,
        "cost": 200,
        "level": 2,
        "quality": "normal",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror", "necrolyte"],
        "weaponSubtype": "wand"
    },
    ember_wand: {
        "name": "Ember Wand",
        "baseDamage": 1,
        "maxDamage": 4,
        "baseMagicDamage": 14,
        "cost": 320,
        "level": 4,
        "quality": "normal",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror", "necrolyte"],
        "weaponSubtype": "wand"
    },
    frost_wand: {
        "name": "Frost Wand",
        "baseDamage": 1,
        "maxDamage": 4,
        "baseMagicDamage": 17,
        "cost": 800,
        "level": 6,
        "quality": "normal",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror", "necrolyte"],
        "weaponSubtype": "wand"
    },
    shock_wand: {
        "name": "Shock Wand",
        "baseDamage": 2,
        "maxDamage": 4,
        "baseMagicDamage": 20,
        "cost": 1100,
        "level": 8,
        "quality": "rare",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror", "necrolyte"],
        "weaponSubtype": "wand"
    },
    arcane_wand: {
        "name": "Arcane Wand",
        "baseDamage": 2,
        "maxDamage": 5,
        "baseMagicDamage": 24,
        "cost": 2200,
        "level": 10,
        "quality": "rare",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror", "necrolyte"],
        "weaponSubtype": "wand"
    },
    void_wand: {
        "name": "Void Wand",
        "baseDamage": 2,
        "maxDamage": 5,
        "baseMagicDamage": 28,
        "cost": 3200,
        "level": 12,
        "quality": "epic",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror", "necrolyte"],
        "weaponSubtype": "wand"
    },
    celestial_wand: {
        "name": "Celestial Wand",
        "baseDamage": 2,
        "maxDamage": 5,
        "baseMagicDamage": 32,
        "cost": 5500,
        "level": 14,
        "quality": "epic",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror", "necrolyte"],
        "weaponSubtype": "wand"
    },
    eternity_wand: {
        "name": "Wand of Eternity",
        "baseDamage": 3,
        "maxDamage": 6,
        "baseMagicDamage": 36,
        "cost": 8000,
        "level": 16,
        "quality": "legendary",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror", "necrolyte"],
        "weaponSubtype": "wand"
    },
    apocalypse_wand: {
        "name": "Apocalypse Wand",
        "baseDamage": 3,
        "maxDamage": 6,
        "baseMagicDamage": 40,
        "cost": 18000,
        "level": 18,
        "quality": "legendary",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror", "necrolyte"],
        "weaponSubtype": "wand"
    },
    cosmic_wand: {
        "name": "Cosmic Wand",
        "baseDamage": 3,
        "maxDamage": 7,
        "baseMagicDamage": 45,
        "cost": 16000,
        "level": 20,
        "quality": "legendary",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror", "necrolyte"],
        "weaponSubtype": "wand"
    },

    // ======================================================
    // TOMES - Cleric (Very Low Melee, High Magic + Healing)
    // ======================================================
    apprentice_tome: {
        "name": "Apprentice Tome",
        "baseDamage": 2,
        "maxDamage": 4,
        "baseMagicDamage": 8,
        "healingBonus": 5,
        "cost": 60,
        "level": 1,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric", "acolyte"],
        "description": "A basic prayer book filled with simple blessings."
    },
    prayer_book: {
        "name": "Prayer Book",
        "baseDamage": 2,
        "maxDamage": 4,
        "baseMagicDamage": 11,
        "healingBonus": 5,
        "cost": 120,
        "level": 2,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric", "acolyte"],
        "description": "Common prayers and hymns for the faithful."
    },
    holy_scriptures: {
        "name": "Holy Scriptures",
        "baseDamage": 2,
        "maxDamage": 5,
        "baseMagicDamage": 14,
        "healingBonus": 6,
        "cost": 180,
        "level": 3,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric", "acolyte"],
        "description": "The core teachings of the faith."
    },
    blessed_tome: {
        "name": "Blessed Tome",
        "baseDamage": 3,
        "maxDamage": 5,
        "baseMagicDamage": 17,
        "healingBonus": 6,
        "cost": 250,
        "level": 4,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric", "acolyte"],
        "description": "Blessed by a traveling priest."
    },
    sacred_texts: {
        "name": "Sacred Texts",
        "baseDamage": 3,
        "maxDamage": 5,
        "baseMagicDamage": 20,
        "healingBonus": 7,
        "cost": 350,
        "level": 5,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric", "acolyte"],
        "description": "Writings from various prophets."
    },
    gospel_of_healing: {
        "name": "Gospel of Healing",
        "baseDamage": 3,
        "maxDamage": 6,
        "baseMagicDamage": 23,
        "healingBonus": 7,
        "cost": 500,
        "level": 6,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "Focused on the healing arts."
    },
    holy_tome: {
        "name": "Holy Tome",
        "baseDamage": 4,
        "maxDamage": 6,
        "baseMagicDamage": 26,
        "healingBonus": 8,
        "cost": 700,
        "level": 7,
        "quality": "rare",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "Radiates faint divine light."
    },
    divine_tome: {
        "name": "Divine Tome",
        "baseDamage": 4,
        "maxDamage": 7,
        "baseMagicDamage": 29,
        "healingBonus": 8,
        "cost": 950,
        "level": 8,
        "quality": "rare",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "Written in gold ink."
    },
    scripture_of_light: {
        "name": "Scripture of Light",
        "baseDamage": 4,
        "maxDamage": 7,
        "baseMagicDamage": 32,
        "healingBonus": 9,
        "cost": 1250,
        "level": 9,
        "quality": "rare",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "Glows in the presence of undead."
    },
    prayers_of_the_faithful: {
        "name": "Prayers of the Faithful",
        "baseDamage": 5,
        "maxDamage": 8,
        "baseMagicDamage": 35,
        "healingBonus": 9,
        "cost": 1600,
        "level": 10,
        "quality": "rare",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "Powerful enough to mend bones."
    },
    tome_of_renewal: {
        "name": "Tome of Renewal",
        "baseDamage": 5,
        "maxDamage": 8,
        "baseMagicDamage": 38,
        "healingBonus": 10,
        "cost": 2100,
        "level": 11,
        "quality": "epic",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "Focused on restoration."
    },
    codex_of_healing: {
        "name": "Codex of Healing",
        "baseDamage": 5,
        "maxDamage": 9,
        "baseMagicDamage": 41,
        "healingBonus": 10,
        "cost": 2700,
        "level": 12,
        "quality": "epic",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "Complete guide to healing."
    },
    gospel_of_life: {
        "name": "Gospel of Life",
        "baseDamage": 6,
        "maxDamage": 9,
        "baseMagicDamage": 44,
        "healingBonus": 11,
        "cost": 3400,
        "level": 13,
        "quality": "epic",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "The word of life itself."
    },
    scripture_of_the_divine: {
        "name": "Scripture of the Divine",
        "baseDamage": 6,
        "maxDamage": 10,
        "baseMagicDamage": 47,
        "healingBonus": 11,
        "cost": 4200,
        "level": 14,
        "quality": "epic",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "Dictated by the gods."
    },
    holy_bible: {
        "name": "Holy Bible",
        "baseDamage": 6,
        "maxDamage": 10,
        "baseMagicDamage": 50,
        "healingBonus": 12,
        "cost": 5100,
        "level": 15,
        "quality": "epic",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "The complete holy text."
    },
    tome_of_miracles: {
        "name": "Tome of Miracles",
        "baseDamage": 7,
        "maxDamage": 11,
        "baseMagicDamage": 53,
        "healingBonus": 12,
        "cost": 6200,
        "level": 16,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "Accounts of actual miracles."
    },
    codex_of_the_chosen: {
        "name": "Codex of the Chosen",
        "baseDamage": 7,
        "maxDamage": 11,
        "baseMagicDamage": 56,
        "healingBonus": 13,
        "cost": 7500,
        "level": 17,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "Only the chosen may read it."
    },
    scripture_of_eternal_light: {
        "name": "Scripture of Eternal Light",
        "baseDamage": 7,
        "maxDamage": 12,
        "baseMagicDamage": 59,
        "healingBonus": 13,
        "cost": 9000,
        "level": 18,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "Radiates constant light."
    },
    gospel_of_salvation: {
        "name": "Gospel of Salvation",
        "baseDamage": 8,
        "maxDamage": 12,
        "baseMagicDamage": 62,
        "healingBonus": 14,
        "cost": 10800,
        "level": 19,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "Promises salvation."
    },
    divine_codex: {
        "name": "Divine Codex",
        "baseDamage": 8,
        "maxDamage": 13,
        "baseMagicDamage": 65,
        "healingBonus": 14,
        "cost": 12800,
        "level": 20,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["cleric"],
        "description": "The word of god made manifest."
    },
    tome_of_the_high_priest: {
        "name": "Tome of the High Priest",
        "baseDamage": 8,
        "maxDamage": 13,
        "baseMagicDamage": 68,
        "healingBonus": 15,
        "cost": 15200,
        "level": 21,
        "quality": "godly",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["high_priest"],
        "description": "Used by the highest authorities."
    },
    scripture_of_creation: {
        "name": "Scripture of Creation",
        "baseDamage": 9,
        "maxDamage": 14,
        "baseMagicDamage": 71,
        "healingBonus": 15,
        "cost": 18000,
        "level": 22,
        "quality": "godly",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["high_priest"],
        "description": "The story of creation."
    },
    codex_of_the_divine: {
        "name": "Codex of the Divine",
        "baseDamage": 9,
        "maxDamage": 14,
        "baseMagicDamage": 74,
        "healingBonus": 16,
        "cost": 21200,
        "level": 23,
        "quality": "godly",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["high_priest"],
        "description": "Record of divine intervention."
    },
    gospel_of_the_gods: {
        "name": "Gospel of the Gods",
        "baseDamage": 9,
        "maxDamage": 15,
        "baseMagicDamage": 77,
        "healingBonus": 16,
        "cost": 25000,
        "level": 24,
        "quality": "godly",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["high_priest"],
        "description": "The direct word of the gods."
    },
    tome_of_creation: {
        "name": "Tome of Creation",
        "baseDamage": 10,
        "maxDamage": 16,
        "baseMagicDamage": 80,
        "healingBonus": 17,
        "cost": 30000,
        "level": 25,
        "quality": "godly",
        "slot": "weapon",
        "weaponSubtype": "tome",
        "allowedClasses": ["high_priest"],
        "description": "The first book ever written."
    },

    // ======================================================
    // STAVES - Balanced (Medium Melee, Medium Magic)
    // ======================================================
    wooden_staff: {
        "name": "Wooden Staff",
        "baseDamage": 4,
        "maxDamage": 8,
        "baseMagicDamage": 4,
        "cost": 0,
        "level": 1,
        "quality": "normal",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "cleric", "druid", "runesmith"],
        "weaponSubtype": "staff"
    },
    apprentice_staff: {
        "name": "Apprentice Staff",
        "baseDamage": 5,
        "maxDamage": 9,
        "baseMagicDamage": 6,
        "cost": 500,
        "level": 2,
        "quality": "normal",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "cleric", "druid", "runesmith"],
        "weaponSubtype": "staff"
    },
    holy_staff: {
        "name": "Holy Staff",
        "baseDamage": 6,
        "maxDamage": 10,
        "baseMagicDamage": 8,
        "cost": 220,
        "level": 3,
        "quality": "normal",
        "slot": "weapon",
        "allowedClasses": ["cleric", "paladin"],
        "weaponSubtype": "staff"
    },
    dark_staff: {
        "name": "Dark Staff",
        "baseDamage": 6,
        "maxDamage": 11,
        "baseMagicDamage": 10,
        "cost": 350,
        "level": 4,
        "quality": "normal",
        "slot": "weapon",
        "allowedClasses": ["warlock", "necrolyte"],
        "weaponSubtype": "staff"
    },
    flame_staff: {
        "name": "Flame Staff",
        "baseDamage": 7,
        "maxDamage": 12,
        "baseMagicDamage": 12,
        "cost": 550,
        "level": 4,
        "quality": "normal",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror"],
        "weaponSubtype": "staff"
    },
    sacred_staff: {
        "name": "Sacred Staff",
        "baseDamage": 8,
        "maxDamage": 14,
        "baseMagicDamage": 14,
        "cost": 550,
        "level": 6,
        "quality": "normal",
        "slot": "weapon",
        "allowedClasses": ["cleric", "paladin"],
        "weaponSubtype": "staff"
    },
    ice_staff: {
        "name": "Ice Staff",
        "baseDamage": 9,
        "maxDamage": 15,
        "baseMagicDamage": 16,
        "cost": 1100,
        "level": 6,
        "quality": "normal",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror"],
        "weaponSubtype": "staff"
    },
    cursed_staff: {
        "name": "Cursed Staff",
        "baseDamage": 9,
        "maxDamage": 16,
        "baseMagicDamage": 18,
        "cost": 1800,
        "level": 7,
        "quality": "rare",
        "slot": "weapon",
        "allowedClasses": ["warlock", "necrolyte"],
        "weaponSubtype": "staff"
    },
    shadow_staff: {
        "name": "Shadow Staff",
        "baseDamage": 10,
        "maxDamage": 17,
        "baseMagicDamage": 20,
        "cost": 1100,
        "level": 8,
        "quality": "rare",
        "slot": "weapon",
        "allowedClasses": ["warlock", "necrolyte"],
        "weaponSubtype": "staff"
    },
    lightning_staff: {
        "name": "Lightning Staff",
        "baseDamage": 11,
        "maxDamage": 18,
        "baseMagicDamage": 22,
        "cost": 1800,
        "level": 8,
        "quality": "rare",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror"],
        "weaponSubtype": "staff"
    },
    necromantic_staff: {
        "name": "Necromantic Staff",
        "baseDamage": 11,
        "maxDamage": 19,
        "baseMagicDamage": 24,
        "cost": 2000,
        "level": 8,
        "quality": "epic",
        "slot": "weapon",
        "allowedClasses": ["necrolyte", "warlock"],
        "weaponSubtype": "staff"
    },
    prophecy_staff: {
        "name": "Prophecy Staff",
        "baseDamage": 12,
        "maxDamage": 20,
        "baseMagicDamage": 26,
        "cost": 2500,
        "level": 9,
        "quality": "epic",
        "slot": "weapon",
        "allowedClasses": ["cleric", "acolyte"],
        "weaponSubtype": "staff"
    },
    divine_staff: {
        "name": "Divine Staff",
        "baseDamage": 13,
        "maxDamage": 22,
        "baseMagicDamage": 28,
        "cost": 2000,
        "level": 10,
        "quality": "rare",
        "slot": "weapon",
        "allowedClasses": ["cleric", "paladin"],
        "weaponSubtype": "staff"
    },
    archmage_staff: {
        "name": "Archmage Staff",
        "baseDamage": 14,
        "maxDamage": 23,
        "baseMagicDamage": 30,
        "cost": 11000,
        "level": 10,
        "quality": "rare",
        "slot": "weapon",
        "allowedClasses": ["mage", "sorceror"],
        "weaponSubtype": "staff"
    },
    void_staff: {
        "name": "Void Staff",
        "baseDamage": 15,
        "maxDamage": 24,
        "baseMagicDamage": 32,
        "cost": 5000,
        "level": 12,
        "quality": "epic",
        "slot": "weapon",
        "allowedClasses": ["warlock", "necrolyte"],
        "weaponSubtype": "staff"
    },
    soul_staff: {
        "name": "Soul Staff",
        "baseDamage": 16,
        "maxDamage": 25,
        "baseMagicDamage": 34,
        "cost": 5500,
        "level": 13,
        "quality": "epic",
        "slot": "weapon",
        "allowedClasses": ["warlock", "necrolyte"],
        "weaponSubtype": "staff"
    },
    celestial_staff: {
        "name": "Celestial Staff",
        "baseDamage": 17,
        "maxDamage": 26,
        "baseMagicDamage": 36,
        "cost": 8000,
        "level": 14,
        "quality": "epic",
        "slot": "weapon",
        "allowedClasses": ["cleric", "acolyte"],
        "weaponSubtype": "staff"
    },
    celestial_rod: {
        "name": "Celestial Rod",
        "baseDamage": 18,
        "maxDamage": 28,
        "baseMagicDamage": 38,
        "cost": 8000,
        "level": 15,
        "quality": "epic",
        "slot": "weapon",
        "allowedClasses": ["cleric", "paladin"],
        "weaponSubtype": "staff"
    },
    eternity_staff: {
        "name": "Staff of Eternity",
        "baseDamage": 19,
        "maxDamage": 30,
        "baseMagicDamage": 40,
        "cost": 11000,
        "level": 16,
        "quality": "legendary",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "cleric"],
        "weaponSubtype": "staff"
    },
    void_dark_staff: {
        "name": "Staff of the Void",
        "baseDamage": 20,
        "maxDamage": 32,
        "baseMagicDamage": 42,
        "cost": 19000,
        "level": 19,
        "quality": "legendary",
        "slot": "weapon",
        "allowedClasses": ["warlock", "necrolyte"],
        "weaponSubtype": "staff"
    },
    apocalypse_staff: {
        "name": "Apocalypse Staff",
        "baseDamage": 21,
        "maxDamage": 34,
        "baseMagicDamage": 44,
        "cost": 50000,
        "level": 18,
        "quality": "legendary",
        "slot": "weapon",
        "allowedClasses": ["mage", "warlock", "sorceror"],
        "weaponSubtype": "staff"
    },
    cosmic_staff: {
        "name": "Cosmic Staff",
        "baseDamage": 22,
        "maxDamage": 36,
        "baseMagicDamage": 46,
        "cost": 22000,
        "level": 20,
        "quality": "legendary",
        "slot": "weapon",
        "allowedClasses": ["mage", "sorceror"],
        "weaponSubtype": "staff"
    },
    gods_scepter: {
        "name": "God's Scepter",
        "baseDamage": 24,
        "maxDamage": 38,
        "baseMagicDamage": 50,
        "cost": 30000,
        "level": 20,
        "quality": "legendary",
        "slot": "weapon",
        "allowedClasses": ["cleric", "high_priest"],
        "weaponSubtype": "staff"
    },

    // ======================================================
    // MACES - Cleric/Paladin (High Melee, Low Magic)
    // ======================================================
    wooden_club: {
        "name": "Wooden Club",
        "baseDamage": 9,
        "maxDamage": 13,
        "baseMagicDamage": 0,
        "cost": 150,
        "level": 1,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["warrior", "paladin", "cleric"]
    },
    iron_mace: {
        "name": "Iron Mace",
        "baseDamage": 13,
        "maxDamage": 19,
        "baseMagicDamage": 0,
        "cost": 400,
        "level": 2,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["warrior", "paladin", "cleric"]
    },
    flanged_mace: {
        "name": "Flanged Mace",
        "baseDamage": 17,
        "maxDamage": 26,
        "baseMagicDamage": 0,
        "cost": 750,
        "level": 3,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["warrior", "paladin", "cleric"]
    },
    battlemace: {
        "name": "Battlemace",
        "baseDamage": 21,
        "maxDamage": 31,
        "baseMagicDamage": 2,
        "cost": 500,
        "level": 4,
        "quality": "normal",
        "slot": "weapon",
        "allowedClasses": ["warrior", "paladin", "cleric"],
        "weaponSubtype": "mace"
    },
    holy_mace: {
        "name": "Holy Mace",
        "baseDamage": 24,
        "maxDamage": 36,
        "baseMagicDamage": 4,
        "cost": 1930,
        "level": 5,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["cleric", "paladin"]
    },
    war_mace: {
        "name": "War Mace",
        "baseDamage": 28,
        "maxDamage": 42,
        "baseMagicDamage": 0,
        "cost": 2400,
        "level": 6,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["warrior", "paladin", "cleric"]
    },
    blessed_mace: {
        "name": "Blessed Mace",
        "baseDamage": 32,
        "maxDamage": 49,
        "baseMagicDamage": 5,
        "cost": 3470,
        "level": 7,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["cleric", "paladin"]
    },
    silver_mace: {
        "name": "Silver Mace",
        "baseDamage": 35,
        "maxDamage": 54,
        "baseMagicDamage": 6,
        "cost": 4400,
        "level": 8,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["cleric", "paladin"]
    },
    crushmaster: {
        "name": "Crushmaster",
        "baseDamage": 39,
        "maxDamage": 58,
        "baseMagicDamage": 0,
        "cost": 4950,
        "level": 9,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["warrior", "paladin", "cleric"]
    },
    divine_mace: {
        "name": "Divine Mace",
        "baseDamage": 43,
        "maxDamage": 65,
        "baseMagicDamage": 7,
        "cost": 6600,
        "level": 10,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["cleric", "paladin"]
    },
    soul_mace: {
        "name": "Soul Mace",
        "baseDamage": 47,
        "maxDamage": 71,
        "baseMagicDamage": 0,
        "cost": 7150,
        "level": 11,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["warrior", "paladin", "cleric"]
    },
    sanctified_mace: {
        "name": "Sanctified Mace",
        "baseDamage": 50,
        "maxDamage": 76,
        "baseMagicDamage": 8,
        "cost": 9240,
        "level": 12,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["cleric", "paladin"]
    },
    judgment: {
        "name": "Judgment",
        "baseDamage": 54,
        "maxDamage": 81,
        "baseMagicDamage": 8,
        "cost": 10720,
        "level": 13,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["cleric", "paladin"]
    },
    templar_mace: {
        "name": "Templar Mace",
        "baseDamage": 58,
        "maxDamage": 87,
        "baseMagicDamage": 9,
        "cost": 12320,
        "level": 14,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["cleric", "paladin"]
    },
    thundermace: {
        "name": "Thundermace",
        "baseDamage": 62,
        "maxDamage": 94,
        "baseMagicDamage": 0,
        "cost": 12750,
        "level": 15,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["warrior", "paladin", "cleric"]
    },
    wrath_of_the_gods: {
        "name": "Wrath of the Gods",
        "baseDamage": 65,
        "maxDamage": 99,
        "baseMagicDamage": 10,
        "cost": 15840,
        "level": 16,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["cleric", "paladin"]
    },
    celestial_crusher: {
        "name": "Celestial Crusher",
        "baseDamage": 68,
        "maxDamage": 104,
        "baseMagicDamage": 10,
        "cost": 17760,
        "level": 17,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["cleric", "paladin"]
    },
    scepter_of_doom: {
        "name": "Scepter of Doom",
        "baseDamage": 73,
        "maxDamage": 110,
        "baseMagicDamage": 0,
        "cost": 18000,
        "level": 18,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["warrior", "paladin", "cleric"]
    },
    apocalypse_mace: {
        "name": "Apocalypse Mace",
        "baseDamage": 77,
        "maxDamage": 117,
        "baseMagicDamage": 11,
        "cost": 21940,
        "level": 19,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["cleric", "paladin"]
    },
    world_mace: {
        "name": "World Mace",
        "baseDamage": 80,
        "maxDamage": 121,
        "baseMagicDamage": 0,
        "cost": 22000,
        "level": 20,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["warrior", "paladin", "cleric"]
    },
    eternity_crusher: {
        "name": "Eternity Crusher",
        "baseDamage": 88,
        "maxDamage": 133,
        "baseMagicDamage": 0,
        "cost": 26400,
        "level": 22,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["warrior", "paladin", "cleric"]
    },
    oblivion_scepter: {
        "name": "Oblivion Scepter",
        "baseDamage": 95,
        "maxDamage": 145,
        "baseMagicDamage": 14,
        "cost": 34320,
        "level": 24,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["cleric", "paladin"]
    },
    genesis_mace: {
        "name": "Genesis Mace",
        "baseDamage": 98,
        "maxDamage": 149,
        "baseMagicDamage": 0,
        "cost": 33750,
        "level": 25,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "mace",
        "allowedClasses": ["warrior", "paladin", "cleric"]
    },

    // ======================================================
    // SWORDS - Warrior/Paladin
    // ======================================================
    iron_sword: {
        "name": "Iron Sword",
        "baseDamage": 8,
        "maxDamage": 14,
        "baseMagicDamage": 0,
        "cost": 0,
        "level": 1,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin"]
    },
    short_sword: {
        "name": "Short Sword",
        "baseDamage": 11,
        "maxDamage": 18,
        "baseMagicDamage": 0,
        "cost": 110,
        "level": 2,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin", "rogue"]
    },
    steel_sword: {
        "name": "Steel Sword",
        "baseDamage": 15,
        "maxDamage": 24,
        "baseMagicDamage": 0,
        "cost": 1000,
        "level": 4,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin"]
    },
    crusader_sword: {
        "name": "Crusader Sword",
        "baseDamage": 18,
        "maxDamage": 30,
        "baseMagicDamage": 5,
        "cost": 500,
        "level": 5,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["paladin", "crusader"]
    },
    bastard_sword: {
        "name": "Bastard Sword",
        "baseDamage": 22,
        "maxDamage": 36,
        "baseMagicDamage": 0,
        "cost": 900,
        "level": 6,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin"]
    },
    ancient_sword: {
        "name": "Ancient Sword",
        "baseDamage": 25,
        "maxDamage": 40,
        "baseMagicDamage": 0,
        "cost": 1200,
        "level": 6,
        "quality": "rare",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin"]
    },
    fire_blade: {
        "name": "Fire Blade",
        "baseDamage": 24,
        "maxDamage": 38,
        "baseMagicDamage": 5,
        "cost": 1500,
        "level": 6,
        "quality": "rare",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin"]
    },
    frozen_blade: {
        "name": "Frozen Blade",
        "baseDamage": 24,
        "maxDamage": 38,
        "baseMagicDamage": 5,
        "cost": 1500,
        "level": 6,
        "quality": "rare",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin"]
    },
    cursed_sword: {
        "name": "Cursed Sword",
        "baseDamage": 28,
        "maxDamage": 44,
        "baseMagicDamage": 0,
        "cost": 1800,
        "level": 7,
        "quality": "rare",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin", "warlock"]
    },
    cursed_blade: {
        "name": "Cursed Blade",
        "baseDamage": 30,
        "maxDamage": 46,
        "baseMagicDamage": 4,
        "cost": 2000,
        "level": 7,
        "quality": "rare",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin", "warlock"]
    },
    greatsword: {
        "name": "Greatsword",
        "baseDamage": 32,
        "maxDamage": 50,
        "baseMagicDamage": 0,
        "cost": 5000,
        "level": 8,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "greatsword",
        "allowedClasses": ["warrior", "paladin"]
    },
    shadowblade: {
        "name": "Shadowblade",
        "baseDamage": 30,
        "maxDamage": 48,
        "baseMagicDamage": 6,
        "cost": 2000,
        "level": 8,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "rogue", "warlock"]
    },
    holy_blade: {
        "name": "Holy Blade",
        "baseDamage": 32,
        "maxDamage": 50,
        "baseMagicDamage": 8,
        "cost": 2500,
        "level": 9,
        "quality": "epic",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["paladin", "cleric"]
    },
    spectral_blade: {
        "name": "Spectral Blade",
        "baseDamage": 32,
        "maxDamage": 50,
        "baseMagicDamage": 8,
        "cost": 2800,
        "level": 9,
        "quality": "epic",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "warlock"]
    },
    excalibur: {
        "name": "Excalibur",
        "baseDamage": 35,
        "maxDamage": 55,
        "baseMagicDamage": 8,
        "cost": 2800,
        "level": 10,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin"]
    },
    infernal_blade: {
        "name": "Infernal Blade",
        "baseDamage": 36,
        "maxDamage": 56,
        "baseMagicDamage": 8,
        "cost": 3000,
        "level": 10,
        "quality": "epic",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "warlock"]
    },
    vampire_blade: {
        "name": "Vampire Blade",
        "baseDamage": 36,
        "maxDamage": 56,
        "baseMagicDamage": 6,
        "cost": 3000,
        "level": 10,
        "quality": "epic",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "warlock"]
    },
    runic_blade: {
        "name": "Runic Blade",
        "baseDamage": 40,
        "maxDamage": 62,
        "baseMagicDamage": 8,
        "cost": 4500,
        "level": 12,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin", "runesmith"]
    },
    champion_sword: {
        "name": "Champion Sword",
        "baseDamage": 42,
        "maxDamage": 64,
        "baseMagicDamage": 0,
        "cost": 4000,
        "level": 12,
        "quality": "epic",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin"]
    },
    void_blade: {
        "name": "Void Blade",
        "baseDamage": 45,
        "maxDamage": 68,
        "baseMagicDamage": 10,
        "cost": 5000,
        "level": 13,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "warlock"]
    },
    titan_blade: {
        "name": "Titan Blade",
        "baseDamage": 48,
        "maxDamage": 72,
        "baseMagicDamage": 0,
        "cost": 5000,
        "level": 13,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin"]
    },
    titanforged_sword: {
        "name": "Titanforged Sword",
        "baseDamage": 50,
        "maxDamage": 76,
        "baseMagicDamage": 10,
        "cost": 7000,
        "level": 14,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin"]
    },
    celestial_blade: {
        "name": "Celestial Blade",
        "baseDamage": 52,
        "maxDamage": 78,
        "baseMagicDamage": 12,
        "cost": 8000,
        "level": 15,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin"]
    },
    heavenly_blade: {
        "name": "Heavenly Blade",
        "baseDamage": 52,
        "maxDamage": 78,
        "baseMagicDamage": 10,
        "cost": 7500,
        "level": 15,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "paladin"]
    },
    hellforged_blade: {
        "name": "Hellforged Blade",
        "baseDamage": 54,
        "maxDamage": 82,
        "baseMagicDamage": 10,
        "cost": 8000,
        "level": 16,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "warlock"]
    },
    godslayer: {
        "name": "Godslayer",
        "baseDamage": 58,
        "maxDamage": 88,
        "baseMagicDamage": 12,
        "cost": 35000,
        "level": 16,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "greatsword",
        "allowedClasses": ["warrior", "paladin"]
    },
    abyssal_blade: {
        "name": "Abyssal Blade",
        "baseDamage": 60,
        "maxDamage": 92,
        "baseMagicDamage": 14,
        "cost": 10000,
        "level": 17,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "warlock"]
    },
    oblivion_blade: {
        "name": "Oblivion Blade",
        "baseDamage": 64,
        "maxDamage": 98,
        "baseMagicDamage": 16,
        "cost": 15000,
        "level": 18,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "warlock"]
    },
    demonic_blade: {
        "name": "Demonic Blade",
        "baseDamage": 66,
        "maxDamage": 100,
        "baseMagicDamage": 14,
        "cost": 14000,
        "level": 18,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["warrior", "warlock"]
    },
    holy_avenger: {
        "name": "Holy Avenger",
        "baseDamage": 62,
        "maxDamage": 95,
        "baseMagicDamage": 18,
        "cost": 6000,
        "level": 12,
        "quality": "epic",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["paladin", "crusader"]
    },
    blade_of_judgement: {
        "name": "Blade of Judgement",
        "baseDamage": 75,
        "maxDamage": 115,
        "baseMagicDamage": 22,
        "cost": 28000,
        "level": 20,
        "quality": "legendary",
        "slot": "weapon",
        "weaponSubtype": "sword",
        "allowedClasses": ["paladin", "crusader"]
    },
    god_blade: {
        "name": "God Blade",
        "baseDamage": 80,
        "maxDamage": 120,
        "baseMagicDamage": 20,
        "cost": 50000,
        "level": 20,
        "quality": "godly",
        "slot": "weapon",
        "weaponSubtype": "greatsword",
        "allowedClasses": ["warrior", "paladin"]
    },
    infinity_blade: {
        "name": "Infinity Blade",
        "baseDamage": 85,
        "maxDamage": 130,
        "baseMagicDamage": 18,
        "cost": 28000,
        "level": 22,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "greatsword",
        "allowedClasses": ["warrior", "paladin"]
    },
    primordial_weapon: {
        "name": "Primordial Weapon",
        "baseDamage": 95,
        "maxDamage": 145,
        "baseMagicDamage": 20,
        "cost": 35000,
        "level": 24,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "greatsword",
        "allowedClasses": ["warrior", "paladin"]
    },
    genesis: {
        "name": "Genesis",
        "baseDamage": 100,
        "maxDamage": 150,
        "baseMagicDamage": 25,
        "cost": 50000,
        "level": 25,
        "quality": "godly",
        "slot": "weapon",
        "weaponSubtype": "greatsword",
        "allowedClasses": ["warrior", "paladin"]
    },

    // ======================================================
    // AXES - Warrior
    // ======================================================
    hand_axe: {
        "name": "Hand Axe",
        "baseDamage": 8,
        "maxDamage": 14,
        "baseMagicDamage": 0,
        "cost": 150,
        "level": 1,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    wood_axe: {
        "name": "Wood Axe",
        "baseDamage": 13,
        "maxDamage": 21,
        "baseMagicDamage": 0,
        "cost": 400,
        "level": 2,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    battle_axe: {
        "name": "Battle Axe",
        "baseDamage": 17,
        "maxDamage": 28,
        "baseMagicDamage": 0,
        "cost": 750,
        "level": 3,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    broad_axe: {
        "name": "Broad Axe",
        "baseDamage": 20,
        "maxDamage": 32,
        "baseMagicDamage": 0,
        "cost": 1200,
        "level": 4,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    giant_axe: {
        "name": "Giant Axe",
        "baseDamage": 22,
        "maxDamage": 36,
        "baseMagicDamage": 0,
        "cost": 500,
        "level": 4,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    reinforced_axe: {
        "name": "Reinforced Axe",
        "baseDamage": 23,
        "maxDamage": 38,
        "baseMagicDamage": 0,
        "cost": 1750,
        "level": 5,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    raiders_axe: {
        "name": "Raider's Axe",
        "baseDamage": 27,
        "maxDamage": 45,
        "baseMagicDamage": 0,
        "cost": 2400,
        "level": 6,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    dire_axe: {
        "name": "Dire Axe",
        "baseDamage": 32,
        "maxDamage": 52,
        "baseMagicDamage": 0,
        "cost": 3150,
        "level": 7,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    great_axe: {
        "name": "Great Axe",
        "baseDamage": 35,
        "maxDamage": 57,
        "baseMagicDamage": 0,
        "cost": 4000,
        "level": 8,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    berserker_axe: {
        "name": "Berserker Axe",
        "baseDamage": 38,
        "maxDamage": 62,
        "baseMagicDamage": 0,
        "cost": 4950,
        "level": 9,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    stormaxe: {
        "name": "Stormaxe",
        "baseDamage": 42,
        "maxDamage": 69,
        "baseMagicDamage": 0,
        "cost": 6000,
        "level": 10,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    bloodaxe: {
        "name": "Bloodaxe",
        "baseDamage": 46,
        "maxDamage": 76,
        "baseMagicDamage": 0,
        "cost": 7150,
        "level": 11,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    titan_axe: {
        "name": "Titan Axe",
        "baseDamage": 49,
        "maxDamage": 80,
        "baseMagicDamage": 0,
        "cost": 8400,
        "level": 12,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    soulcleaver: {
        "name": "Soulcleaver",
        "baseDamage": 52,
        "maxDamage": 86,
        "baseMagicDamage": 0,
        "cost": 9750,
        "level": 13,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    warbringer: {
        "name": "Warbringer",
        "baseDamage": 57,
        "maxDamage": 93,
        "baseMagicDamage": 0,
        "cost": 11200,
        "level": 14,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    dread_axe: {
        "name": "Dread Axe",
        "baseDamage": 61,
        "maxDamage": 100,
        "baseMagicDamage": 0,
        "cost": 12750,
        "level": 15,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    voidedge_axe: {
        "name": "Voidedge Axe",
        "baseDamage": 64,
        "maxDamage": 106,
        "baseMagicDamage": 0,
        "cost": 14400,
        "level": 16,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    ruinbringer: {
        "name": "Ruinbringer",
        "baseDamage": 67,
        "maxDamage": 110,
        "baseMagicDamage": 0,
        "cost": 16150,
        "level": 17,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    cataclysm_axe: {
        "name": "Cataclysm Axe",
        "baseDamage": 71,
        "maxDamage": 117,
        "baseMagicDamage": 0,
        "cost": 18000,
        "level": 18,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    sundering_axe: {
        "name": "Sundering Axe",
        "baseDamage": 76,
        "maxDamage": 124,
        "baseMagicDamage": 0,
        "cost": 19950,
        "level": 19,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    world_splitter: {
        "name": "World Splitter",
        "baseDamage": 79,
        "maxDamage": 129,
        "baseMagicDamage": 0,
        "cost": 22000,
        "level": 20,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    infinity_axe: {
        "name": "Infinity Axe",
        "baseDamage": 86,
        "maxDamage": 141,
        "baseMagicDamage": 0,
        "cost": 26400,
        "level": 22,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    oblivion_cleaver: {
        "name": "Oblivion Cleaver",
        "baseDamage": 93,
        "maxDamage": 154,
        "baseMagicDamage": 0,
        "cost": 31200,
        "level": 24,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },
    axe_of_genesis: {
        "name": "Axe of Genesis",
        "baseDamage": 97,
        "maxDamage": 159,
        "baseMagicDamage": 0,
        "cost": 33750,
        "level": 25,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "axe",
        "allowedClasses": ["warrior", "paladin"]
    },

    // ======================================================
    // HAMMERS - Warrior/Paladin
    // ======================================================
    iron_maul: {
        "name": "Iron Maul",
        "baseDamage": 9,
        "maxDamage": 13,
        "baseMagicDamage": 0,
        "cost": 150,
        "level": 1,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    stone_hammer: {
        "name": "Stone Hammer",
        "baseDamage": 13,
        "maxDamage": 20,
        "baseMagicDamage": 0,
        "cost": 400,
        "level": 2,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    war_hammer: {
        "name": "War Hammer",
        "baseDamage": 18,
        "maxDamage": 27,
        "baseMagicDamage": 0,
        "cost": 750,
        "level": 3,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    warhammer: {
        "name": "Warhammer",
        "baseDamage": 20,
        "maxDamage": 30,
        "baseMagicDamage": 0,
        "cost": 400,
        "level": 3,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    flanged_hammer: {
        "name": "Flanged Hammer",
        "baseDamage": 21,
        "maxDamage": 31,
        "baseMagicDamage": 0,
        "cost": 1200,
        "level": 4,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    ironbane_hammer: {
        "name": "Ironbane Hammer",
        "baseDamage": 24,
        "maxDamage": 37,
        "baseMagicDamage": 0,
        "cost": 1750,
        "level": 5,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    runic_hammer: {
        "name": "Runic Hammer",
        "baseDamage": 29,
        "maxDamage": 44,
        "baseMagicDamage": 0,
        "cost": 2400,
        "level": 6,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin", "runesmith"]
    },
    forge_hammer: {
        "name": "Forge Hammer",
        "baseDamage": 33,
        "maxDamage": 50,
        "baseMagicDamage": 0,
        "cost": 3150,
        "level": 7,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    thunder_maul: {
        "name": "Thunder Maul",
        "baseDamage": 36,
        "maxDamage": 56,
        "baseMagicDamage": 0,
        "cost": 4000,
        "level": 8,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    skullcracker: {
        "name": "Skullcracker",
        "baseDamage": 40,
        "maxDamage": 60,
        "baseMagicDamage": 0,
        "cost": 4950,
        "level": 9,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    mjolnite_hammer: {
        "name": "Mjolnite Hammer",
        "baseDamage": 44,
        "maxDamage": 67,
        "baseMagicDamage": 0,
        "cost": 6000,
        "level": 10,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    earthshaker: {
        "name": "Earthshaker",
        "baseDamage": 48,
        "maxDamage": 74,
        "baseMagicDamage": 0,
        "cost": 7150,
        "level": 11,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    titans_fist: {
        "name": "Titan's Fist",
        "baseDamage": 52,
        "maxDamage": 78,
        "baseMagicDamage": 0,
        "cost": 8400,
        "level": 12,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    siegebreaker: {
        "name": "Siegebreaker",
        "baseDamage": 55,
        "maxDamage": 84,
        "baseMagicDamage": 0,
        "cost": 9750,
        "level": 13,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    devastator: {
        "name": "Devastator",
        "baseDamage": 59,
        "maxDamage": 91,
        "baseMagicDamage": 0,
        "cost": 11200,
        "level": 14,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    ragnarok_maul: {
        "name": "Ragnarok Maul",
        "baseDamage": 64,
        "maxDamage": 97,
        "baseMagicDamage": 0,
        "cost": 12750,
        "level": 15,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    colossus_hammer: {
        "name": "Colossus Hammer",
        "baseDamage": 67,
        "maxDamage": 103,
        "baseMagicDamage": 0,
        "cost": 14400,
        "level": 16,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    godbreaker: {
        "name": "Godbreaker",
        "baseDamage": 70,
        "maxDamage": 108,
        "baseMagicDamage": 0,
        "cost": 16150,
        "level": 17,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    voidhammer: {
        "name": "Voidhammer",
        "baseDamage": 75,
        "maxDamage": 114,
        "baseMagicDamage": 0,
        "cost": 18000,
        "level": 18,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin", "runesmith"]
    },
    eclipse_maul: {
        "name": "Eclipse Maul",
        "baseDamage": 79,
        "maxDamage": 121,
        "baseMagicDamage": 0,
        "cost": 19950,
        "level": 19,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    world_ender: {
        "name": "World Ender",
        "baseDamage": 82,
        "maxDamage": 125,
        "baseMagicDamage": 0,
        "cost": 22000,
        "level": 20,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    eternity_maul: {
        "name": "Eternity Maul",
        "baseDamage": 90,
        "maxDamage": 138,
        "baseMagicDamage": 0,
        "cost": 26400,
        "level": 22,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    oblivion_hammer: {
        "name": "Oblivion Hammer",
        "baseDamage": 98,
        "maxDamage": 150,
        "baseMagicDamage": 0,
        "cost": 31200,
        "level": 24,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },
    hammer_of_creation: {
        "name": "Hammer of Creation",
        "baseDamage": 101,
        "maxDamage": 155,
        "baseMagicDamage": 0,
        "cost": 33750,
        "level": 25,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "hammer",
        "allowedClasses": ["warrior", "paladin"]
    },

    // ======================================================
    // DAGGERS - Rogue
    // ======================================================
    iron_dagger: {
        "name": "Iron Dagger",
        "baseDamage": 5,
        "maxDamage": 8,
        "baseMagicDamage": 0,
        "cost": 150,
        "level": 1,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    rusty_dagger: {
        "name": "Rusty Dagger",
        "baseDamage": 1,
        "maxDamage": 2,
        "baseMagicDamage": 0,
        "cost": 0,
        "level": 1,
        "quality": "poor",
        "slot": "weapon",
        "weaponSubtype": "dagger"
    },
    rusty_shiv: {
        "name": "Rusty Shiv",
        "baseDamage": 3,
        "maxDamage": 5,
        "baseMagicDamage": 0,
        "cost": 0,
        "level": 1,
        "quality": "poor",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    dagger: {
        "name": "Dagger",
        "baseDamage": 4,
        "maxDamage": 7,
        "baseMagicDamage": 0,
        "cost": 80,
        "level": 1,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "allowedClasses": ["rogue", "hunter"]
    },
    bone_pick: {
        "name": "Bone Pick",
        "baseDamage": 5,
        "maxDamage": 9,
        "baseMagicDamage": 0,
        "cost": 280,
        "level": 2,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    poison_dagger: {
        "name": "Poison Dagger",
        "baseDamage": 5,
        "maxDamage": 8,
        "baseMagicDamage": 0,
        "cost": 150,
        "level": 2,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "poisonChance": 0.2
    },
    copper_stiletto: {
        "name": "Copper Stiletto",
        "baseDamage": 6,
        "maxDamage": 10,
        "baseMagicDamage": 0,
        "cost": 400,
        "level": 3,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    throwing_knife: {
        "name": "Throwing Knife",
        "baseDamage": 7,
        "maxDamage": 11,
        "baseMagicDamage": 0,
        "cost": 520,
        "level": 4,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    assassin_blade: {
        "name": "Assassin's Blade",
        "baseDamage": 8,
        "maxDamage": 13,
        "baseMagicDamage": 0,
        "cost": 700,
        "level": 5,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    shadow_fang: {
        "name": "Shadow Fang",
        "baseDamage": 6,
        "maxDamage": 10,
        "baseMagicDamage": 0,
        "cost": 900,
        "level": 6,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    venom_spike: {
        "name": "Venom Spike",
        "baseDamage": 7,
        "maxDamage": 12,
        "baseMagicDamage": 0,
        "cost": 1200,
        "level": 7,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue",
        "poisonChance": 0.25
    },
    midnight_dirk: {
        "name": "Midnight Dirk",
        "baseDamage": 8,
        "maxDamage": 13,
        "baseMagicDamage": 0,
        "cost": 1500,
        "level": 8,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    blacksteel_dagger: {
        "name": "Blacksteel Dagger",
        "baseDamage": 9,
        "maxDamage": 15,
        "baseMagicDamage": 0,
        "cost": 2000,
        "level": 9,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    shadowstep_blade: {
        "name": "Shadowstep Blade",
        "baseDamage": 25,
        "maxDamage": 53,
        "baseMagicDamage": 0,
        "cost": 6000,
        "level": 10,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    phantom_edge: {
        "name": "Phantom Edge",
        "baseDamage": 10,
        "maxDamage": 17,
        "baseMagicDamage": 0,
        "cost": 2600,
        "level": 10,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    soul_piercer: {
        "name": "Soul Piercer",
        "baseDamage": 11,
        "maxDamage": 18,
        "baseMagicDamage": 0,
        "cost": 3400,
        "level": 11,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    serpent_tooth: {
        "name": "Serpent's Tooth",
        "baseDamage": 12,
        "maxDamage": 20,
        "baseMagicDamage": 0,
        "cost": 4200,
        "level": 12,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue",
        "poisonChance": 0.35
    },
    venomfang_dagger: {
        "name": "Venomfang Dagger",
        "baseDamage": 29,
        "maxDamage": 62,
        "baseMagicDamage": 0,
        "cost": 8400,
        "level": 12,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    twilight_shard: {
        "name": "Twilight Shard",
        "baseDamage": 31,
        "maxDamage": 66,
        "baseMagicDamage": 0,
        "cost": 9750,
        "level": 13,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    eclipse_blade: {
        "name": "Eclipse Blade",
        "baseDamage": 13,
        "maxDamage": 22,
        "baseMagicDamage": 0,
        "cost": 5200,
        "level": 13,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    dusk_blade: {
        "name": "Dusk Blade",
        "baseDamage": 33,
        "maxDamage": 71,
        "baseMagicDamage": 0,
        "cost": 11200,
        "level": 14,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    wraithblade: {
        "name": "Wraithblade",
        "baseDamage": 14,
        "maxDamage": 23,
        "baseMagicDamage": 0,
        "cost": 6200,
        "level": 14,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    crimson_fang: {
        "name": "Crimson Fang",
        "baseDamage": 36,
        "maxDamage": 77,
        "baseMagicDamage": 0,
        "cost": 12750,
        "level": 15,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    shadow_reaver: {
        "name": "Shadow Reaver",
        "baseDamage": 16,
        "maxDamage": 26,
        "baseMagicDamage": 0,
        "cost": 7500,
        "level": 15,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    void_stiletto: {
        "name": "Void Stiletto",
        "baseDamage": 17,
        "maxDamage": 28,
        "baseMagicDamage": 0,
        "cost": 9000,
        "level": 16,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    death_whisper: {
        "name": "Death's Whisper",
        "baseDamage": 18,
        "maxDamage": 30,
        "baseMagicDamage": 0,
        "cost": 11000,
        "level": 17,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    oblivion_shard: {
        "name": "Oblivion Shard",
        "baseDamage": 20,
        "maxDamage": 32,
        "baseMagicDamage": 0,
        "cost": 13500,
        "level": 18,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    reaper_kiss: {
        "name": "Reaper's Kiss",
        "baseDamage": 21,
        "maxDamage": 34,
        "baseMagicDamage": 0,
        "cost": 16000,
        "level": 19,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    bloodmoon_fang: {
        "name": "Bloodmoon Fang",
        "baseDamage": 23,
        "maxDamage": 37,
        "baseMagicDamage": 0,
        "cost": 20000,
        "level": 20,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue",
        "poisonChance": 0.4
    },
    shade_piercer: {
        "name": "Shade Piercer",
        "baseDamage": 48,
        "maxDamage": 103,
        "baseMagicDamage": 0,
        "cost": 24150,
        "level": 21,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    eternal_night: {
        "name": "Eternal Night",
        "baseDamage": 25,
        "maxDamage": 40,
        "baseMagicDamage": 0,
        "cost": 25000,
        "level": 21,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    nights_edge: {
        "name": "Night's Edge",
        "baseDamage": 51,
        "maxDamage": 108,
        "baseMagicDamage": 0,
        "cost": 26400,
        "level": 22,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    shadowbane_dagger: {
        "name": "Shadowbane",
        "baseDamage": 27,
        "maxDamage": 43,
        "baseMagicDamage": 0,
        "cost": 31000,
        "level": 22,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    silencer: {
        "name": "Silencer",
        "baseDamage": 29,
        "maxDamage": 46,
        "baseMagicDamage": 0,
        "cost": 38000,
        "level": 23,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    void_fang: {
        "name": "Void Fang",
        "baseDamage": 53,
        "maxDamage": 114,
        "baseMagicDamage": 0,
        "cost": 28750,
        "level": 23,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    abyssal_thorn: {
        "name": "Abyssal Thorn",
        "baseDamage": 32,
        "maxDamage": 50,
        "baseMagicDamage": 0,
        "cost": 47000,
        "level": 24,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    infinity_shard: {
        "name": "Infinity Shard",
        "baseDamage": 57,
        "maxDamage": 121,
        "baseMagicDamage": 0,
        "cost": 33750,
        "level": 25,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },
    omega_blade: {
        "name": "Omega Blade",
        "baseDamage": 35,
        "maxDamage": 55,
        "baseMagicDamage": 0,
        "cost": 60000,
        "level": 25,
        "quality": "godly",
        "slot": "weapon",
        "weaponSubtype": "dagger",
        "classRestriction": "rogue"
    },

    // ======================================================
    // BOWS - Hunter/Ranger
    // ======================================================
    training_bow: {
        "name": "Training Bow",
        "baseDamage": 7,
        "maxDamage": 12,
        "baseMagicDamage": 0,
        "cost": 0,
        "level": 1,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    short_bow: {
        "name": "Short Bow",
        "baseDamage": 11,
        "maxDamage": 20,
        "baseMagicDamage": 0,
        "cost": 400,
        "level": 2,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    hunting_bow: {
        "name": "Hunting Bow",
        "baseDamage": 15,
        "maxDamage": 26,
        "baseMagicDamage": 0,
        "cost": 750,
        "level": 3,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    longbow: {
        "name": "Longbow",
        "baseDamage": 18,
        "maxDamage": 30,
        "baseMagicDamage": 0,
        "cost": 450,
        "level": 4,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    composite_bow: {
        "name": "Composite Bow",
        "baseDamage": 22,
        "maxDamage": 38,
        "baseMagicDamage": 0,
        "cost": 1750,
        "level": 5,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    elven_bow: {
        "name": "Elven Bow",
        "baseDamage": 26,
        "maxDamage": 44,
        "baseMagicDamage": 2,
        "cost": 2800,
        "level": 6,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    war_bow: {
        "name": "War Bow",
        "baseDamage": 30,
        "maxDamage": 52,
        "baseMagicDamage": 0,
        "cost": 3150,
        "level": 7,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    recurve_bow: {
        "name": "Recurve Bow",
        "baseDamage": 34,
        "maxDamage": 58,
        "baseMagicDamage": 0,
        "cost": 4000,
        "level": 8,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    cursed_bow: {
        "name": "Cursed Bow",
        "baseDamage": 35,
        "maxDamage": 60,
        "baseMagicDamage": 0,
        "cost": 600,
        "level": 5,
        "quality": "rare",
        "slot": "weapon",
        "weaponSubtype": "bow"
    },
    elven_shortbow: {
        "name": "Elven Shortbow",
        "baseDamage": 38,
        "maxDamage": 64,
        "baseMagicDamage": 0,
        "cost": 4950,
        "level": 9,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    dragonslayer_bow: {
        "name": "Dragonslayer Bow",
        "baseDamage": 42,
        "maxDamage": 72,
        "baseMagicDamage": 4,
        "cost": 35000,
        "level": 10,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    darkwood_bow: {
        "name": "Darkwood Bow",
        "baseDamage": 46,
        "maxDamage": 78,
        "baseMagicDamage": 0,
        "cost": 7150,
        "level": 11,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    storm_bow: {
        "name": "Storm Bow",
        "baseDamage": 50,
        "maxDamage": 84,
        "baseMagicDamage": 0,
        "cost": 8400,
        "level": 12,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    ironwood_bow: {
        "name": "Ironwood Bow",
        "baseDamage": 54,
        "maxDamage": 90,
        "baseMagicDamage": 0,
        "cost": 9750,
        "level": 13,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    phantom_bow: {
        "name": "Phantom Bow",
        "baseDamage": 60,
        "maxDamage": 100,
        "baseMagicDamage": 6,
        "cost": 28000,
        "level": 14,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    siege_bow: {
        "name": "Siege Bow",
        "baseDamage": 64,
        "maxDamage": 106,
        "baseMagicDamage": 0,
        "cost": 12750,
        "level": 15,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    shadow_bow: {
        "name": "Shadow Bow",
        "baseDamage": 68,
        "maxDamage": 112,
        "baseMagicDamage": 0,
        "cost": 14400,
        "level": 16,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    voidbow: {
        "name": "Voidbow",
        "baseDamage": 72,
        "maxDamage": 118,
        "baseMagicDamage": 0,
        "cost": 16150,
        "level": 17,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    celestial_bow: {
        "name": "Celestial Bow",
        "baseDamage": 76,
        "maxDamage": 124,
        "baseMagicDamage": 0,
        "cost": 18000,
        "level": 18,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    devastation_bow: {
        "name": "Devastation Bow",
        "baseDamage": 80,
        "maxDamage": 130,
        "baseMagicDamage": 0,
        "cost": 19950,
        "level": 19,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    world_bow: {
        "name": "World Bow",
        "baseDamage": 84,
        "maxDamage": 136,
        "baseMagicDamage": 0,
        "cost": 22000,
        "level": 20,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    eternity_bow: {
        "name": "Eternity Bow",
        "baseDamage": 88,
        "maxDamage": 142,
        "baseMagicDamage": 0,
        "cost": 24150,
        "level": 21,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    oblivion_bow: {
        "name": "Oblivion Bow",
        "baseDamage": 92,
        "maxDamage": 148,
        "baseMagicDamage": 0,
        "cost": 26400,
        "level": 22,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    apex_bow: {
        "name": "Apex Bow",
        "baseDamage": 96,
        "maxDamage": 154,
        "baseMagicDamage": 0,
        "cost": 28750,
        "level": 23,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    genesis_bow: {
        "name": "Genesis Bow",
        "baseDamage": 100,
        "maxDamage": 160,
        "baseMagicDamage": 0,
        "cost": 31200,
        "level": 24,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },
    omega_bow: {
        "name": "Omega Bow",
        "baseDamage": 104,
        "maxDamage": 166,
        "baseMagicDamage": 0,
        "cost": 33750,
        "level": 25,
        "quality": "normal",
        "slot": "weapon",
        "weaponSubtype": "bow",
        "allowedClasses": ["hunter", "ranger", "archer"]
    },

    // ======================================================
    // CROSSBOWS - Hunter/Ranger
    // ======================================================
    light_crossbow: {
        "name": "Light Crossbow",
        "baseDamage": 8,
        "maxDamage": 14,
        "baseMagicDamage": 0,
        "level": 1,
        "quality": "normal",
        "weaponSubtype": "crossbow",
        "allowedClasses": ["archer", "hunter", "ranger", "rogue"],
        "cost": 80,
        "sellValue": 25
    },
    crossbow: {
        "name": "Crossbow",
        "baseDamage": 14,
        "maxDamage": 22,
        "baseMagicDamage": 0,
        "level": 3,
        "quality": "normal",
        "weaponSubtype": "crossbow",
        "allowedClasses": ["archer", "hunter", "ranger", "rogue"],
        "cost": 180,
        "sellValue": 55
    },
    heavy_crossbow: {
        "name": "Heavy Crossbow",
        "baseDamage": 22,
        "maxDamage": 36,
        "baseMagicDamage": 0,
        "level": 6,
        "quality": "normal",
        "weaponSubtype": "crossbow",
        "allowedClasses": ["archer", "hunter", "ranger"],
        "cost": 420,
        "sellValue": 130
    },
    arbalest: {
        "name": "Arbalest",
        "baseDamage": 35,
        "maxDamage": 55,
        "baseMagicDamage": 0,
        "level": 10,
        "quality": "rare",
        "weaponSubtype": "crossbow",
        "allowedClasses": ["archer", "hunter", "ranger"],
        "cost": 1200,
        "sellValue": 380
    },
    void_crossbow: {
        "name": "Void Crossbow",
        "baseDamage": 55,
        "maxDamage": 85,
        "baseMagicDamage": 10,
        "level": 15,
        "quality": "epic",
        "weaponSubtype": "crossbow",
        "allowedClasses": ["archer", "hunter", "ranger"],
        "cost": 6500,
        "sellValue": 2000
    },
    genesis_crossbow: {
        "name": "Crossbow of Genesis",
        "baseDamage": 80,
        "maxDamage": 120,
        "baseMagicDamage": 20,
        "level": 22,
        "quality": "legendary",
        "weaponSubtype": "crossbow",
        "allowedClasses": ["archer", "hunter", "ranger"],
        "cost": 25000,
        "sellValue": 8000
    },

    // ======================================================
    // ORBS - Mage/Sorceror
    // ======================================================
    crystal_orb: {
        "name": "Crystal Orb",
        "baseDamage": 2,
        "maxDamage": 4,
        "baseMagicDamage": 10,
        "level": 2,
        "quality": "normal",
        "weaponSubtype": "orb",
        "allowedClasses": ["mage", "sorceror", "warlock"],
        "cost": 100,
        "sellValue": 30
    },
    flame_orb: {
        "name": "Flame Orb",
        "baseDamage": 3,
        "maxDamage": 5,
        "baseMagicDamage": 16,
        "level": 5,
        "quality": "normal",
        "weaponSubtype": "orb",
        "allowedClasses": ["mage", "sorceror", "warlock"],
        "cost": 400,
        "sellValue": 120
    },
    void_orb: {
        "name": "Void Orb",
        "baseDamage": 4,
        "maxDamage": 6,
        "baseMagicDamage": 28,
        "level": 10,
        "quality": "rare",
        "weaponSubtype": "orb",
        "allowedClasses": ["mage", "sorceror", "warlock"],
        "cost": 1800,
        "sellValue": 560
    },
    chaos_orb: {
        "name": "Chaos Orb",
        "baseDamage": 5,
        "maxDamage": 8,
        "baseMagicDamage": 45,
        "level": 16,
        "quality": "epic",
        "weaponSubtype": "orb",
        "allowedClasses": ["mage", "sorceror", "warlock"],
        "cost": 9000,
        "sellValue": 2800
    },
    genesis_orb: {
        "name": "Orb of Genesis",
        "baseDamage": 6,
        "maxDamage": 10,
        "baseMagicDamage": 70,
        "level": 22,
        "quality": "legendary",
        "weaponSubtype": "orb",
        "allowedClasses": ["mage", "sorceror", "warlock"],
        "cost": 28000,
        "sellValue": 9000
    },

    // ======================================================
    // SHADOW ORBS - Warlock
    // ======================================================
    shadow_orb: {
        "name": "Shadow Orb",
        "baseDamage": 3,
        "maxDamage": 5,
        "baseMagicDamage": 18,
        "level": 5,
        "quality": "rare",
        "weaponSubtype": "orb",
        "allowedClasses": ["warlock", "necrolyte"],
        "cost": 600,
        "sellValue": 185
    },
    soul_orb: {
        "name": "Soul Orb",
        "baseDamage": 4,
        "maxDamage": 7,
        "baseMagicDamage": 36,
        "level": 12,
        "quality": "epic",
        "weaponSubtype": "orb",
        "allowedClasses": ["warlock", "necrolyte"],
        "cost": 4200,
        "sellValue": 1300
    },
    void_shadow_orb: {
        "name": "Void Shadow Orb",
        "baseDamage": 5,
        "maxDamage": 9,
        "baseMagicDamage": 55,
        "level": 19,
        "quality": "legendary",
        "weaponSubtype": "orb",
        "allowedClasses": ["warlock", "necrolyte"],
        "cost": 18000,
        "sellValue": 5500
    },

    // ======================================================
    // BONE WEAPONS - Monster Drops
    // ======================================================
    bone_club: {
        "name": "Bone Club",
        "baseDamage": 5,
        "maxDamage": 9,
        "baseMagicDamage": 0,
        "cost": 0,
        "level": 2,
        "quality": "poor",
        "slot": "weapon",
        "weaponSubtype": "club"
    },

    // ======================================================
    // DRAGON-THEMED WEAPONS
    // ======================================================
    dragon_kin_blade: {
        "name": "Dragon-kin Blade",
        "type": "weapon",
        "weaponSubtype": "sword",
        "baseDamage": 17,
        "maxDamage": 26,
        "baseMagicDamage": 4,
        "level": 6,
        "quality": "rare",
        "modifiers": ["flaming"],
        "description": "Forged from the tooth of a young dragon. Still warm to the touch.",
        "allowedClasses": ["warrior", "paladin"],
        "cost": 1100,
        "sellValue": 550
    },
    scale_piercer: {
        "name": "Scale Piercer",
        "type": "weapon",
        "weaponSubtype": "axe",
        "baseDamage": 22,
        "maxDamage": 34,
        "level": 8,
        "quality": "epic",
        "modifiers": ["piercing"],
        "description": "An axe designed to slip between dragon scales.",
        "allowedClasses": ["warrior", "paladin"],
        "cost": 1700,
        "sellValue": 850
    },
    drake_tongue_blade: {
        "name": "Drake-Tongue Blade",
        "type": "weapon",
        "weaponSubtype": "sword",
        "baseDamage": 19,
        "maxDamage": 30,
        "baseMagicDamage": 6,
        "level": 7,
        "quality": "legendary",
        "modifiers": ["life_drain", "cursed"],
        "description": "Tempered in drake blood. Powerful but hungers for your life force.",
        "allowedClasses": ["warrior", "paladin"],
        "cost": 2100,
        "sellValue": 1050
    },
    soul_drinker_sword: {
        "name": "Soul Drinker",
        "type": "weapon",
        "weaponSubtype": "sword",
        "baseDamage": 24,
        "maxDamage": 38,
        "level": 9,
        "quality": "legendary",
        "modifiers": ["life_drain"],
        "description": "Feeds on the souls of your enemies, returning vitality to you.",
        "allowedClasses": ["warrior", "paladin"],
        "cost": 2900,
        "sellValue": 1450
    },
    dragon_piercer: {
        "name": "Dragon Piercer",
        "type": "weapon",
        "weaponSubtype": "axe",
        "baseDamage": 24,
        "maxDamage": 36,
        "level": 8,
        "quality": "epic",
        "modifiers": ["armor_breaking"],
        "description": "Forged specifically to pierce dragon scales.",
        "allowedClasses": ["warrior", "paladin"],
        "cost": 1800,
        "sellValue": 900
    },
    purified_blade: {
        "name": "Purified Sacred Blade",
        "type": "weapon",
        "weaponSubtype": "sword",
        "baseDamage": 19,
        "maxDamage": 30,
        "baseMagicDamage": 8,
        "level": 7,
        "quality": "epic",
        "modifiers": ["holy"],
        "description": "A holy blade purified of its curse. Radiates divine light.",
        "allowedClasses": ["paladin", "cleric"],
        "cost": 2000,
        "sellValue": 1000
    },
    wyrm_slayer: {
        "name": "Wyrm-Slayer",
        "type": "weapon",
        "weaponSubtype": "sword",
        "baseDamage": 21,
        "maxDamage": 33,
        "baseMagicDamage": 5,
        "level": 7,
        "quality": "epic",
        "modifiers": ["holy"],
        "description": "A blade blessed against wyrms and lesser dragons.",
        "allowedClasses": ["paladin", "cleric"],
        "cost": 1900,
        "sellValue": 950
    },
    soul_render: {
        "name": "Soul Render",
        "type": "weapon",
        "weaponSubtype": "sword",
        "baseDamage": 24,
        "maxDamage": 38,
        "level": 9,
        "quality": "legendary",
        "modifiers": ["life_drain"],
        "description": "Feeds on the souls of your enemies, returning vitality to you.",
        "allowedClasses": ["warrior", "warlock"],
        "cost": 2900,
        "sellValue": 1450
    },
    ancient_dragon_slayer: {
        "name": "Ancient Dragon-Slayer",
        "type": "weapon",
        "weaponSubtype": "greatsword",
        "baseDamage": 58,
        "maxDamage": 92,
        "baseMagicDamage": 25,
        "level": 23,
        "quality": "godly",
        "modifiers": ["dragon_bane", "giant_slayer", "vorpal"],
        "description": "A legendary blade from the Dragon War. Every swing remembers the Calamity.",
        "allowedClasses": ["warrior", "paladin", "crusader"],
        "cost": 45000,
        "sellValue": 22500
    },
    calamity_breaker: {
        "name": "Calamity Breaker",
        "type": "weapon",
        "weaponSubtype": "greatsword",
        "baseDamage": 62,
        "maxDamage": 98,
        "baseMagicDamage": 20,
        "level": 24,
        "quality": "godly",
        "modifiers": ["dragon_bane", "armor_breaking", "thunderous"],
        "description": "Forged specifically to end the Calamity Dragon. It thirsts.",
        "allowedClasses": ["warrior", "paladin"],
        "cost": 52000,
        "sellValue": 26000
    },
    dragonscale_blade: {
        "name": "Dragonscale Blade",
        "type": "weapon",
        "weaponSubtype": "sword",
        "baseDamage": 48,
        "maxDamage": 76,
        "baseMagicDamage": 18,
        "level": 22,
        "quality": "legendary",
        "modifiers": ["dragon_bane", "flaming"],
        "description": "Wrapped in the scales of an ancient dragon. It recognizes its own.",
        "allowedClasses": ["warrior", "paladin", "ranger"],
        "cost": 38000,
        "sellValue": 19000
    },
    dragon_heart_sword: {
        "name": "Dragonheart Blade",
        "type": "weapon",
        "weaponSubtype": "sword",
        "baseDamage": 52,
        "maxDamage": 84,
        "baseMagicDamage": 30,
        "level": 23,
        "quality": "legendary",
        "modifiers": ["dragon_bane", "life_drain", "flaming"],
        "description": "Forged around a still-beating dragon heart. It pulses with rage.",
        "allowedClasses": ["warrior", "warlock", "paladin"],
        "cost": 48000,
        "sellValue": 24000
    },

    // ======================================================
    // MAGICAL ITEMS
    // ======================================================
    magical_butterknife: {
        "name": "Magical Butterknife",
        "slot": "weapon",
        "quality": "godly",
        "type": "dagger",
        "level": 25,
        "baseDamage": 10000,
        "maxDamage": 10000,
        "baseMagicDamage": 10000,
        "description": "A Godly weapon that should only be used by the gods to spread butter on toast."
    }
};

console.log('✅ Weapons loaded with damage ranges:', Object.keys(WEAPONS).length, 'weapons');