// WEAPONS DATABASE
// Generated by Dungeon Editor on 2/20/2026, 5:42:21 PM

const QUALITY_CONFIG = {
    poor:      { bonusPct: 0.00, color: '#808080', name: 'Poor'      },
    normal:    { bonusPct: 0.10, color: '#00FF00', name: 'Normal'    },
    rare:      { bonusPct: 0.25, color: '#0099FF', name: 'Rare'      },
    epic:      { bonusPct: 0.40, color: '#9933FF', name: 'Epic'      },
    legendary: { bonusPct: 0.60, color: '#FF9900', name: 'Legendary' },
    godly:     { bonusPct: 0.85, color: '#FF0000', name: 'Godly'     }
};

const WEAPONS = {
};
console.log('✅ Weapons loaded with damage ranges:', Object.keys(WEAPONS).length, 'weapons');